### ISSUE TITLE
Temperature initialization bug

### ISSUE THREAD

**Issue by plovely** [underworldcode/UWGeodynamics#100]
Initializing a model with the following thermal boundary conditions:
_Model.set_temperatureBCs(top=273.15 * u.degK, 
                         bottom=1573.15 * u.degK, 
                         materials=[(air, 273.15 * u.degK), (stickyAir, 273.15 * u.degK), (water, 273.15 * u.degK)])_

Produces several anomalies in the thermal field
![temp initialization error](https://user-images.githubusercontent.com/30320218/54615866-cd023080-4a2c-11e9-8ac3-759322460cf8.png)
if materials are defined in the following order:
_air...
stickyAir...
uppercrust...
lowercrust...
lithospheric_mantle...
asthenosphere...
water..._

The initialization is smooth (correct) if air, stickyAir and water are listed as the first three materials.

**Comment by rbeucher** [comment]
Yes it is a known bug. I fixed it the dev branch. I just merged the fix in master...
