### ISSUE TITLE
Composite viscosity is producing incorrect results in select cases

### ISSUE THREAD

**Issue by plovely** [underworldcode/UWGeodynamics#112]
Hi Romain,

I am having trouble with composite viscosities in select cases.  In the screenshot below, I have used a composite viscosity for the mantle. Each of the two viscous creep models that I have combined have magnitudes everywhere greater than 1e19, but I'm getting a composite viscosity many orders of magnitude smaller.  I will email you a notebook that shows the example.

![image](https://user-images.githubusercontent.com/30320218/55510974-0c33a280-5625-11e9-9906-8fd8c13d4fd0.png)

Thanks,
Peter

**Comment by rbeucher** [comment]
Hi Peter,

Yes send me an example and I will have a look

**Comment by rbeucher** [comment]
Thanks for finding this!

**Comment by rbeucher** [comment]
Fix is included in version 2.7.6
