### ISSUE TITLE
Allow modification of melt polynom coefficient

### ISSUE THREAD

**Issue by BenedicteCT** [underworldcode/UWGeodynamics#115]
There are currently three solidus/liquidus defined (Crustal, Mid_Crustal & Mantle) in the melt function.

I would like to modify the melt polynom coefficient for each of these (it is not possible to change these values from the Jupyter Notebook itself and the actual values can be only read in  GitHub resources folder).

**Comment by rbeucher** [comment]
Hi @BenedicteCT 

It is not possible to modify the Solidus / Liquidus defined. I could add that possibility but I am not sure that is a good idea. I have not played much with them but the initial idea was to populate the registries with different curves used by different authors, different context etc.

Now the way forward in your case is to define your own Solidus and Liquidus:

```
import UWGeodynamics as GEO

mySolidus = GEO.Solidus(A1=..., A2=..., A3=..., A4=...)
myLiquidus = GEO.Solidus(A1=..., A2=..., A3=..., A4=...)
```

**Comment by BenedicteCT** [comment]
Thanks that seem to work.
