### ISSUE TITLE
PT path for Lagrangian Particles: stepwise Pressure record

### ISSUE THREAD

**Issue by BenedicteCT** [underworldcode/UWGeodynamics#116]
The Pressure recorded on Lagrangian Particles as (Lag_Grid.add_tracked_field(Model.pressureField, name="LagGridPress", units=u.megapascal, dataType="float") is discontinuous, showing steps in pressure  (see screen shot1).
![Screen Shot1](https://user-images.githubusercontent.com/48540100/56261175-5c2e6100-611d-11e9-8834-167bda1e57c3.png)

However, plotting against y (screen shot2) yields a smooth curve.
![Screen Shot2](https://user-images.githubusercontent.com/48540100/56261189-68b2b980-611d-11e9-8da9-7fa25a84e650.png)

Is there any possibility to record a smoothed instead of discretised pressure in order to get a continuous PT trajectory ?

**Comment by rbeucher** [comment]
Hi @BenedicteCT ,

Was the first plot done right after Model inititialization, meaning the pressure is the lithostatic pressure?

**Comment by BenedicteCT** [comment]
![Screen Shot 2019-04-17 at 3 19 45 pm](https://user-images.githubusercontent.com/48540100/56262950-4c664b00-6124-11e9-88c1-8bedac776af6.png)
After having run model init, the Pressure profile looks like the attached screenshot.

**Comment by rbeucher** [comment]
OK that's fine. But what about the first plot you posted. Was it just after the model init or after reading at least one solve?

**Comment by BenedicteCT** [comment]
The two first plots are generated through post processing (python script) of the data recorded on Lagrangian particles after the model has finished running.

**Comment by julesghub** [comment]
@BenedicteCT Q1/P0 elements for Stokes (the default FEM element types in underworld) will produce a discontinuous pressure solutions across elements, so the jumps aren't surprising.

@rbeucher is the Model.pressureField projected? If not, projecting should help, although it'll be less accurate and high gradients could cause oscillations.

**Comment by rbeucher** [comment]
@julian you mean on the mesh? I will check but I'm pretty sure it's not.

**Comment by julesghub** [comment]
> @Julian you mean on the mesh? I will check but I'm pretty sure it's not.

Yes

**Comment by rbeucher** [comment]
Hi Benedicte,

So it's not really an issue but more a consequence of the type of elements we use by default in Underworld. The pressure is calculated on discrete elements Q0 that basically give us a value of the pressure for each cell and the transition from one element to one neighbour is slightly discontinuous (or very if the resolution is poor).

If I understand the plot you sent me you basically have a set of tracers with different depths... 

I could use some tricks to make it look smoother but that won't make it more accurate...the temperature is better resolved which explains why your second plot is smoother.

You could increase the resolution and that should make things better.

Now Q0 elements are clearly not ideal,  you could use Q1 elements which can resolve the pressure gradient inside elements.  I am working on it now but I want to test things properly.

Romain

**Comment by rbeucher** [comment]
#131 More documentation coming
