### ISSUE TITLE
thermal advection error

### ISSUE THREAD

**Issue by plovely** [underworldcode/UWGeodynamics#117]
Hi Romain,

After seeing some unexpected behavior in the thermal evolution of several models, I constructed a very simple linear-viscous model that stretches in a homogeneous manner, and in which thermal diffusivity is orders of magnitude too small (such that diffusion should be negligible).  

Absent diffusion, temperature contours should track the material field; however, they do not.  In the two figures below,  I apply to the column a stretching factor of 2 over 1 Myr.  The first figure shows the initial configuration and the second at the end of stretching (1 Myr).  Contours show temperature (300 to 1570 K with 141.1 K interval) and colors show material.  

![image](https://user-images.githubusercontent.com/30320218/56376577-d5858c80-61cd-11e9-9e29-475c81c63606.png)

![image](https://user-images.githubusercontent.com/30320218/56376625-fbab2c80-61cd-11e9-8a7f-3ec25405839d.png)

You can see that temperature advects more slowly than the material.  

I stopped stretching and continued to run the model an additional 100 Myr, during which time the thermal field does not change, verifying that indeed diffusion is negligible over the time scale or rifting and much longer time scales.

I'll email you the notebook I've been using to investigate.

Thanks,
Peter

**Comment by rbeucher** [comment]
Just a quick question. Do you use a fixed condition at the base or an heat flow?

**Comment by plovely** [comment]
Fixed temperature at the base.  Temperature is also fixed at the top and everywhere in the air.

**Comment by rbeucher** [comment]
OK I think that makes sense then but will have a closer look next week.

**Comment by rbeucher** [comment]
OK @plovely 

Based on the tests I run today. I think the problem comes from the advection diffusion method used. The default is SUPG which is essentially a diffusion method and that will not work very well if the Peclet number is high. We have the Semi-Lagrangian method although it is only available in the dev branch... I run some tests and it works fine in your case. Let me see how I can make it available to you asap... 
@julesghub  Comments?

**Comment by julesghub** [comment]
Yep, SUPG doesn't handle high peclet numbers well, >1e6.
The SLADE method does and allows for larger timestep sizes too.

At present the SLADE implementation isn't robust, that's why it's in dev. Let's look at it on Friday.

**Comment by plovely** [comment]
Thanks, I would like to give the SLADE method a try, if possible.  Is it in the dev branch of UWGeo or only UW2?  If it's in UWGeo, how do I access it?

I went to this extreme example with a very large Peclet number after seeing some inconsistencies bewteen UW and 1-D thermal models (e.g. Jarvis & McKenzie 1980) for more typical cases.  In the example I provided, if you use a typical diffusivity (e.g. 7e-7 m**2/sec) the Peclet number should be acceptable (less than 1e4, correct?) but the  geothermal gradient and heat flow at end of rifting still seem too small.

**Comment by plovely** [comment]
By the way, for the more typical case, I calculate Pe = L * v / alpha, where L is the characteristic length (I used 100,000m, the vertical dimension of the model; is this correct?), v is the velocity (~4cm/yr ~ 1e-9 m/s is approximately the velocity magnitude), and alpha is the diffusivity, (1e-6 m**2/s), which gives Pe = 100

**Comment by rbeucher** [comment]
version 2.8 should be available soon

**Comment by rbeucher** [comment]
will try to make SLADE available again

**Comment by plovely** [comment]
Thanks, Romain.  Do you have an ETA on v2.8?  Not trying to rush you, just planning ahead.

**Comment by rbeucher** [comment]
You can try to use SLADE by using that option:

`GEO.rcParams["advection.diffusion.method"] = "SLCN"`

**Comment by rbeucher** [comment]
Actually no, I need to update one more thing

**Comment by rbeucher** [comment]
This is now solved in 2.8. There is also an example that covers the model described in that thread.
