### ISSUE TITLE
Missing 0 in weakened lower crust

### ISSUE THREAD

**Issue by LukeMondy** [underworldcode/UWGeodynamics#120]
I think this:
https://github.com/underworldcode/UWGeodynamics/blob/647914cb0bbbb1ee0eae63f32aa070495687b939/UWGeodynamics/ressources/PlasticRheologies.json#L104
is supposed to have an extra 0 in front, as per:
https://github.com/LukeMondy/lithospheric_modelling_recipe/blob/b76603d4d83eda302aa599a392068035f8633e54/lmrRheologyLibrary.xml#L964

**Comment by rbeucher** [comment]
Thanks Luke
