### ISSUE TITLE
Restarting the model

### ISSUE THREAD

**Issue by clairemallard** [underworldcode/UWGeodynamics#121]
Hi Romain,

Just to let you know that in your restarting session in https://uwgeodynamics.readthedocs.io/en/latest/User%20Guide.html#restarting-the-model

you wrote:

Model.run_for(2.0 * u.megayears, restartStep=-1, restartFolder="your_restart_folder")

but it looks like it is:

Model.run_for(2.0 * u.megayears, restartStep=-1, restartDir="your_restart_folder")

Cheers
Claire

**Comment by rbeucher** [comment]
OK Thanks @clairemallard  76b45d562c44a5a4fef4a44798e7032467772429
