### ISSUE TITLE
Magnus UWGeodynamics: AttributeError: module 'underworld' has no attribute 'rank'

### ISSUE THREAD

**Issue by ofbodur** [underworldcode/UWGeodynamics#122]
Hello Romain,

I tried to run an UWGeodynamics model in Magnus yesterday. I followed the steps you provided in Pawsey Magnus section of the documentation. 

`shifter pull docker:underworldcode/uwgeodynamics:magnus`

uploaded my .py file, created .slurm and submitted the job.
Then, I got the following error:

`WARNING: skipping mount of image's /tmp. The file or directory already exists in the container and will not be bind mounted from the image. This could happen because the system administrator configured Shifter to create or mount resources in the container whose path conflicts with the contents of the image.
An uncaught exception was encountered on processor 38.
Traceback (most recent call last):
  File "ProtoSCS_subd_10_wideweak.py", line 13, in <module>
    import UWGeodynamics as GEO
  File "/usr/local/lib/python3.5/dist-packages/UWGeodynamics/__init__.py", line 575, in <module>
    if (underworld.rank() == 0) and not _in_doctest():
AttributeError: module 'underworld' has no attribute 'rank'`

What do you think the problem might be?
Cheers
Omer

**Comment by rbeucher** [comment]
Hi @ofbodur 

Try the "latest" image not magnus

**Comment by rbeucher** [comment]
Let me know if it works an I will get rid of the `magnus` tag once and for all

**Comment by ofbodur** [comment]
Hello Romain,

I just tried it with "latest" image:  Got similar error

`WARNING: skipping mount of image's /tmp. The file or directory already exists in the container and will not be bind mounted from the image. This could happen because the system administrator configured Shifter to create or mount resources in the container whose path conflicts with the contents of the image.
An uncaught exception was encountered on processor 14.
Traceback (most recent call last):
  File "ProtoSCS_subd_10_wideweak.py", line 13, in <module>
    import UWGeodynamics as GEO
  File "/usr/local/lib/python3.5/dist-packages/UWGeodynamics/__init__.py", line 575, in <module>
    if (underworld.rank() == 0) and not _in_doctest():
AttributeError: module 'underworld' has no attribute 'rank'
`

**Comment by rbeucher** [comment]
Can you copy your slurm file please?

**Comment by ofbodur** [comment]
Slurm file:

`
#!/bin/bash

#SBATCH --nodes=2
#SBATCH --time=12:00:00
#SBATCH --account=q97

echo "PRINTING ENVIRONMENT"
env

echo "PRINTING SLURM SCRIPT"
scontrol show job ${SLURM_JOBID} -ddd

module load shifter

srun -n48 shifter run --mpi underworldcode/uwgeodynamics:magnus python ProtoSCS_subd_10_wideweak.py
`

slurm.out file:


[slurm-3596421.txt](https://github.com/underworldcode/UWGeodynamics/files/3182308/slurm-3596421.txt)

**Comment by rbeucher** [comment]
Well if you are using that file you are still using the 'magnus' image...

**Comment by ofbodur** [comment]
oh, you are right. So, loading the latest image from shifter is not enough?

**Comment by rbeucher** [comment]
No it's not. You must explicitly tell slurm which image to use to build the container

**Comment by ofbodur** [comment]
Thanks Romain, it is working now :)
