### ISSUE TITLE
About stress tensor

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/UWGeodynamics#123]
Hi~Dr. Romain
Recently, I'm interesting in stress field during the surface process in continental-extension environment , I wonder how to calculate stress xx, xy , yy in UWGeodynamics and make outputs. I want to establish the principle stresses filed in every point in future.

If there's no way now , I can take my time to try with underworld 2

Best

**Comment by rbeucher** [comment]
Hi @cgw0814 ,

You can access the stress tensor using 'Model.projStressTensor'

best
R

**Comment by cgw0814** [comment]
Thanks Dr. Romain, got it, because I use docker and I have yet to note renewed version, sorry to disturb you @@

**Comment by rbeucher** [comment]
Not a pb at all. Happy to help!
