### ISSUE TITLE
GEO.shapes.Box

### ISSUE THREAD

**Issue by patrice-rey** [underworldcode/UWGeodynamics#125]
Hi Romain
It looks like the option "GEO.shapes.Box" no longer works.  
Is this correct?
Cheers
Patrice

**Comment by rbeucher** [comment]
Hi Patrice,

There's no reason it should not work. Do you have an example?

**Comment by patrice-rey** [comment]
It's the Pull-Apart model, I am using the GEO.shapes.Box to define fault damage using:

DamageFault1Shape = GEO.shapes.Box(minX=0.0 * u.kilometer, maxX=192. * u.kilometer,
                                   minY=145. * u.kilometer, maxY=159. * u.kilometer,
                                   bottom=-40. * u.kilometer, top=-5. * u.kilometer)

I then got an error message saying that GEO.shapes doesn't have a Box option.

**Comment by rbeucher** [comment]
I have just tried this

```
import UWGeodynamics as GEO


DamageFault1Shape = GEO.shapes.Box(minX=0.0 * u.kilometer, maxX=192. * u.kilometer,
minY=145. * u.kilometer, maxY=159. * u.kilometer,
bottom=-40. * u.kilometer, top=-5. * u.kilometer)
```
And I don't have any error. Can you give me a bit more detail about where you are running the code, the
output of GEO.__version__ too please.

**Comment by patrice-rey** [comment]
... my apology, my .pbs was pointing to  underworld_v2.7.7 instead of uwgeodynamics_v2.7.7
Sorry.

**Comment by rbeucher** [comment]
No worries.
