### ISSUE TITLE
Passive tracers documentation

### ISSUE THREAD

**Issue by andresrcorcho** [underworldcode/UWGeodynamics#126]
The documentation of the passive tracers methods is out of data

**Comment by julesghub** [comment]
How so? Can you create a "small" snippet example. Thanks.

**Comment by andresrcorcho** [comment]
Hi Julian, I hope you are well

sorry for the lack of details!

I thought the documentation of the
"Model.add_passive_tracers(vertices=[x,y])" method of UWGeodynamics was
wrong inside the code, but It was really only wrong at the webpage.

As you can see here:

https://uwgeodynamics.readthedocs.io/en/latest/User%20Guide.html#passive-tracers

SPTracers =
Model.add_passive_tracers(vertices=[ListToNd(SPTracersC[0]),ListToNd(SPTracersC[1])])
#This was the original snipet I tried


sorry for the inconvenience,

Andres
