### ISSUE TITLE
create a 3D small rectangular layerings the middle of the model

### ISSUE THREAD

**Issue by HanyMKhalil** [underworldcode/UWGeodynamics#127]
Dear Romain,

I wanted to create a 3d rectangular thin layer in the middle of my 3D model to act as a linear weakness zone, however most of the layer shapes are in 2D. is there a way to define the box shape in the 3D so that I can elongate it?

Thanks a lot

**Comment by rbeucher** [comment]
Hi @HanyMKhalil , 
You can define shapes in 3D by combining `halfspaces`. You can also define a function that defines a shape and returns True when a point coordinate is located inside.
Have a look at https://uwgeodynamics.readthedocs.io/en/latest/User%20Guide.html#the-material-object

scroll down to Half spaces

I hope this helps.

Romain

**Comment by HanyMKhalil** [comment]
Dear Romain,
Yes, it works fine, thanks alot
