### ISSUE TITLE
Docker images for UWGeo 2.8 are not on DockerHub

### ISSUE THREAD

**Issue by LukeMondy** [underworldcode/UWGeodynamics#129]
Hello,

I tried to upgrade to the newest version with `docker pull underworldcode/uwgeodynamics`, but it says I already have the latest version. Running a model reports:
`Running with UWGeodynamics version 2.7.7`

Thanks!
Luke

**Comment by rbeucher** [comment]
Hi Luke

Not they are not there yet. I am working on it right now. 
Should not be long.

Romain

**Comment by rbeucher** [comment]
Hi Luke,

I have pushed the image. Give it a go. Let me know if there is any issue.

**Comment by LukeMondy** [comment]
I've got the image now. I will test it out and see how it goes.
