### ISSUE TITLE
About PostSolveHook problems

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/UWGeodynamics#134]
Hi~ Romain
I try to get Model.projstresstensor information by following programm
`
tTracer      = [GEO.nd(Model.time)]
Stress_xx = [0.]
Stress_yy = [0.]
Stress_xy = [0.]

def postSolveHook():
    global tTracer, Stress_xx, Stress_yy, Stress_xy
    tTracer.append(GEO.nd(Model.time))
    Stress_xx.append(        
        Model.projStressTensor[0].evaluate(Model.mesh)[0])    
    Stress_yy.append(        
        Model.projStressTensor[1].evaluate(Model.mesh)[0])    
    Stress_xy.append(        
        Model.projStressTensor[2].evaluate(Model.mesh)[0])

Model.postSolveHook = postSolveHook`

similar as examples/1_09_ViscoElasticShear.ipynb

tTracer      = [GEO.nd(Model.time)]
previousStress_xy  = [0.]
totalStress_xy  = [0.]

def postSolveHook():
    global tTracer, previousStress_xy, totalStress_xy
    tTracer.append(GEO.nd(Model.time))
    previousStress_xy.append(
        Model._previousStressField[2].evaluate(Model.swarm)[0])
    totalStress_xy.append(        
        Model._stressFn[2].evaluate(Model.swarm)[0])

Model.postSolveHook = postSolveHook`

postSolveHook function was executed smoothly but no output in xmdf files for these parameters I defined, so the function in examples is.

**Comment by rbeucher** [comment]
Hi @cgw0814 ,

Yes I am aware of that. That should be fixed in the last version. See #132 
I am unavailable for the few days but @julesghub  can help if needed.

Romain

**Comment by cgw0814** [comment]
Thanks @rbeucher , I have checked the examples/1_10_Viscoelastoplasticity-in-simple-shear.ipynb was renewed, however the programs in docker was not a renewed version. Anyway, thanks for giving me the answer.

best

cgw0814

**Comment by cgw0814** [comment]
I'm sorry to disturb you. It's difficult to install the UWGeodynamics in machines, I just wait for the renewed program of docker file. BTW, does underworld team will provide the python 2 version of docker later? I found the latest docker file in docker hub is in python 3 version.

**Comment by rbeucher** [comment]
The Underworld code/UWGeodynamics:latest should have everything you need.

**Comment by cgw0814** [comment]
Yeah, I checked the time of Last modified in underworldcode/uwgeodynamics:latest docker file is a month ago and examples/1_10_Viscoelastoplasticity-in-simple-shear.ipynb is old version whether by typing command for latest of docker file in terminal or downloading docker file by kitematic

I tried to modify

> Model.postSolveHook = postSolveHook

into 

> Model.post_solve_functions["Stress Record"] = postSolveHook

still no output in xdmf file as same before

I thought docker file in docker hub is not renewed after you solve the problem addressed in issue #132 8 days ago

But it's ok, I can make the model in this docker file until renewed version is published.  I'm not hurry now. Thanks a lot!!!

best

**Comment by cgw0814** [comment]
OK!! I installed locally including 'compiled underworld and pip3 install UWGeodynamics' 2.8.1b then tried to execute /examples/1_10_Viscoelastoplasticity-in-simple-shear.ipynb `https://github.com/underworldcode/UWGeodynamics/blob/master/examples/1_10_Viscoelastoplasticity-in-simple-shear.ipynb`

I just wonder, does the previousStress_xy, totalStress_xy are recorded in Model.projStressField?

**Comment by rbeucher** [comment]
Sorry, I have been away for a while. Have you found what you needed?  I am not sure I understand the last question.

**Comment by rbeucher** [comment]
I am closing this. Feel free to reopen if needed.
