### ISSUE TITLE
hdf5 erro 

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/UWGeodynamics#136]
I import UWGeodynamics successfully and try to run the tutorials 1

the screen shows 

> AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio

when the Model_run execute

![model-run failed](https://user-images.githubusercontent.com/38973778/64326743-1bb47e80-cffd-11e9-9ba5-041510004305.JPG)

I have installed h5py by

> CC=/home/ncku/intel/compilers_and_libraries_2019.1.144/linux/mpi/intel64/bin/mpicc  HDF5_MPI="ON" HDF5_DIR=/data/bin/hdf5-1.10.1  pip3 install h5py

so I confuse how could I solve this problem

**Comment by julesghub** [comment]
Looks like your h5py was built with mpi support.
To double check run 
```bash
python -c 'import h5py; print(h5py.get_config().mpi)
```

Was hdf5 built with mpi support? To find out.
```bash 
grep -i parallel  $HDF5_DIR/lib/libhdf5.settings
```

**Comment by cgw0814** [comment]
Thanks @julesghub , I have make it by building parallel-hdf5 and python -c 'import h5py; print(h5py.get_config().mpi) shows "true"

then reinstall the underworld and UWGeodynamics.

They run smoothiy with mpirun

**Comment by julesghub** [comment]
Great! I'll close this ticket. Feel free to reopen
