### ISSUE TITLE
Issue with adding passive tracers

### ISSUE THREAD

**Issue by royarnab18** [underworldcode/UWGeodynamics#137]
Hello everyone,
I have been getting this error message  while trying to add passive tracers with the command Model.add_passive_tracers().The tracer is on a non linear surface. Could someone please give any suggestions.

ValueErrorTraceback (most recent call last)
<ipython-input-44-420388873d3e> in <module>()
      3 interface_y = GEO.nd(lightMaterial.top)
      4 
----> 5 interface1 = Model.add_passive_tracers(name="Interface1", vertices=[interface_x , interface_y ])

/opt/UWGeodynamics/UWGeodynamics/_model.py in add_passive_tracers(self, name, vertices, particleEscape, centroids, zOnly)
   1806                                      vertices=vertices,
   1807                                      particleEscape=particleEscape,
-> 1808                                      zOnly=zOnly)
   1809 
   1810         else:

/opt/UWGeodynamics/UWGeodynamics/_utils.py in __init__(self, mesh, velocityField, name, vertices, particleEscape, shapeType, zOnly)
     73 
     74         for dim, _ in enumerate(vertices):
---> 75             points[:, dim] = vertices[dim]
     76 
     77         self.swarm = Swarm(mesh=mesh, particleEscape=particleEscape)

ValueError: setting an array element with a sequence.

**Comment by rbeucher** [comment]
Hi @royarnab, can you post the part of your code that triggers the error?

**Comment by royarnab18** [comment]
Hi @rbeucher, thanks for responding. Here is the code. The tracer line can be obtained for heavyMaterial.top and lightMaterial.bottom. However when i try to apply it to the interface between the two layer, the error is triggered. The interface between the two layers is sinuous

heavyMaterial = Model.add_material(name="Heavy 
  Material",shape=GEO.shapes.Layer2D(top=Model.top, bottom= heavyShape))
lightMaterial = Model.add_material(name="Light 
  Material",shape=GEO.shapes.Layer2D(top=heavyMaterial.bottom, bottom=Model.bottom))

import numpy as np

interface_x = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), 1000)
interface_y = GEO.nd(lightMaterial.top)

TracerLine = Model.add_passive_tracers(name="TracerLine", vertices=[interface_x, interface_y])

**Comment by arijitlaik** [comment]
Hi @royarnab18, I guess Layer2D is for 2d box-like shape with model.maxCoord [0] model.maxCoord [1] as its x limits,
If you would like to make a sinuous interface, you can use conditions to assign material properties above or below the interface, or use a polygonal approximation.
and an example:
``` python
import glucifer as glucifer
import underworld.function as fn
import UWGeodynamics as GEO
import numpy as np

model = GEO.Model()

heavyMaterial = model.add_material(name="Heavy Material")
lightMaterial = model.add_material(name="Light Material")


x = fn.input()[0]
y = fn.input()[1]-2*6400.

sinInterface = 1600.*fn.math.sin(x/3200.)  # or your choice of function


conditions = [(y > sinInterface, lightMaterial.index),
              (True, heavyMaterial.index)]

model.materialField.data[:] = fn.branching.conditional(
    conditions).evaluate(model.swarm)


xP = np.linspace(GEO.nd(model.minCoord[0]), GEO.nd(model.maxCoord[0]), 100)
yP = 1600.*np.sin(xP/3200.)+2*6400.
interfaceTracer = model.add_passive_tracers(
    name="Interface", vertices=[xP, yP])

f = glucifer.Figure()
f.Points(model.swarm, model.materialField)
f.Points(interfaceTracer, pointSize=5,)
f.show()

```

**Comment by royarnab18** [comment]
Hi @arijitlaik Thank you for the reply. Your solution works. I think f.Points(interfaceTracer, pointSize=5,) needs a .swarm after interfaceTracer , otherwise it works. Thanks to everyone.

**Comment by arijitlaik** [comment]
@royarnab18 welcome and no, it does not.

**Comment by arijitlaik** [comment]
@royarnab18 kindly close issue if you feel it is resolved
