### ISSUE TITLE
Surface Swarm Doesn't Track inflow Boundaries

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/UWGeodynamics#14]
Surface Swarms could track the inflow from boundary, for use cases in compression, and or [convergence](https://github.com/rbeucher/UWGeodynamics/blob/development/tutorials/Tutorial_5_Convergence_Model.ipynb)
![sd](https://user-images.githubusercontent.com/10157121/37816322-a7a21b30-2e98-11e8-8d76-80bfa53a1096.png)

**Comment by arijitlaik** [comment]
@rbeucher @julesghub @RebeccaFarrington what should be the idea way to implement this, i was thinking of a 1d interpolation after every timestep, or a swarm variable instead

**Comment by rbeucher** [comment]
I have something in store for that. Will share it with you and we can work it out.

**Comment by arijitlaik** [comment]
Cool :)

**Comment by arijitlaik** [comment]
@rbeucher email this to me maybe, please?

**Comment by arijitlaik** [comment]
Share? :)

**Comment by arijitlaik** [comment]
This one can be closed now, I guess adding a passive tracer with only vertical advection can resolve this.
