### ISSUE TITLE
Docker images on Dockerhub don't appear to be using master branch

### ISSUE THREAD

**Issue by LukeMondy** [underworldcode/UWGeodynamics#141]
Hello,

I was trying to use the newer post_solve_hook functions, detailed here:
https://github.com/underworldcode/UWGeodynamics/blob/master/docs/source/User%20Guide.rst#pre--post-solve-hook-functions

But when I get the latest docker image from dockerhub, it doesn't work - and it appears the UWGeo code is not the same as on GitHub.

Looking here: https://github.com/underworldcode/underworld2/blob/ea248261c19de26ab64cd1b548843737addcbb3a/docs/development/docker/underworld2/Dockerfile#L44
it looks like the UWGeo code in the Docker image is set to the development branch, rather than master.

I'm not sure I've tracked that down right though.

Any ideas?

Cheers,
Luke

**Comment by rbeucher** [comment]
@julesghub ? I think the image is pointing to the dev branch.

**Comment by julesghub** [comment]
err, I'm confused. The image looks is pointing to the development, but `GEO.__version__` is 2.8.2 as per the commands below. What are we after here?

```bash 
[py3] julian@tank:~/codes/UWGeodynamics (development) $ docker pull underworldcode/uwgeodynamics:latest
latest: Pulling from underworldcode/uwgeodynamics
Digest: sha256:79e9ce87105078a5ab02bf5ace24962b7cd07f8345c2862b340aa42afb1519c0
Status: Image is up to date for underworldcode/uwgeodynamics:latest
[py3] julian@tank:~/codes/UWGeodynamics (development) $ docker run -it --rm underworldcode/uwgeodynamics:latest bash
jovyan@24898fe97088:~$ ipython -c 'import UWGeodynamics as GEO; print(GEO.__version__)'
loaded rc file /usr/local/lib/python3.5/dist-packages/UWGeodynamics/uwgeo-data/uwgeodynamicsrc
2.8.2
```

**Comment by rbeucher** [comment]
The master branch of the UW image should get the master of UWGeo.
The dev branch should get the dev branch...
Looks like for now they both get UWGeo dev

**Comment by julesghub** [comment]
ok, then looks like underworld v2.8.1 is pulling the wrong UWGeo.

**Comment by rbeucher** [comment]
I only keep the major and minor numbers in sync. The last one is for UWGeo only.
so 2.8 is fine.

**Comment by rbeucher** [comment]
OK I think this is fixed now. The images are rebuilding. 
I have forced UWGeo reinstall so that when someone commits to the UWGeo it does trigger a rebuild and pull the changes...
