### ISSUE TITLE
Error trying to use with pyBadlands

### ISSUE THREAD

**Issue by raghugram** [underworldcode/UWGeodynamics#151]
Hi,
I am using UWGeodynamics 2.8.2 in docker. The link to pyBadlands seems broken.

GEO.surfaceProcesses.Badlands() call is generating this error.

First with, "import pyBadlands"( with badlands latest in github or with pip install badlands)
and even after installing pyBadlands-serial, 
the error is with "from pyBadlands.model import Model as BadlandsModel"

Am I using wrong version of badlands?

**Comment by raghugram** [comment]
Alright,my bad.
 I missed the instructions in "Dockerfile". Now badlands is also installed and linked. 

Maybe the installation instructions/surface processes can make a reference to this file for installation of badlands in the docker correctly because the other versions(github, pip) of badlands installation have issues linking with UWGeodynamics?

This issue can be closed.

**Comment by rbeucher** [comment]
Do you build you own Dockerfile or do you use the one from Docker cloud.

I just checked our Docker and import seems OK.

The coupling with Badlands is not very well documented... I agree. Feel free to make more suggestions. I am closing this now.

**Comment by rbeucher** [comment]
Thanks for trying the code! Don't forget to "star" the repo if you find it useful!
