### ISSUE TITLE
Viscosity problem when replicating Tutorial_1 in Underworld2

### ISSUE THREAD

**Issue by alexstruc** [underworldcode/UWGeodynamics#153]
Dear developers:
I am trying to replicate the Tutorial_1 of UWGeodynamics in Underworld2. To test the reliability of the model, I input the identical viscosity and plasticity parameters with their units. However, my UW2 model gives me different vertical viscosity profile compared with the solved viscosity profile of Tutorial_1.
Here is the comparison of the two results. The first picture comes from the Tutorial_1, and the second one is for my UW2 model.
![image](https://user-images.githubusercontent.com/50648269/70983724-2bf7f180-20f4-11ea-8aaa-d5257fd84427.png)
![image](https://user-images.githubusercontent.com/50648269/70984559-abd28b80-20f5-11ea-8ff7-f8e53630796d.png)

I attach my code file as text here.
[viscosity test for Tutorial_1 in UW2.txt](https://github.com/underworldcode/UWGeodynamics/files/3972578/viscosity.test.for.Tutorial_1.in.UW2.txt)

I don't understand what causes the big difference. Hope to get your reply.
Thanks a lot
Alexstruc

**Comment by patrice-rey** [comment]
Hi Alex
Log scale ?
Patrice

**Comment by alexstruc** [comment]
Hello, Patrice
Yes. You are right. The problem is my viscosity scale. I get the same profile without using the log scale. Haha, It is a stupid mistake.
Thanks a lot for your help.
Alexstruc
