### ISSUE TITLE
pint v0.10 broken with UWG

### ISSUE THREAD

**Issue by jmansour** [underworldcode/UWGeodynamics#158]
This is a known issue, but just adding here as a reminder.

**Comment by rbeucher** [comment]
Dear @jmansour, Thank you for your support! Could you please be a bit more explicit when describing your issues?

**Comment by jmansour** [comment]
Ok! I assume you were aware of this as someone updated the Dockerfile to use `pint v0.9` instead of `pint v0.10`.   Here is the relevant discussion:

https://github.com/underworldcode/underworld2/issues/453#issuecomment-577189597

**Comment by rbeucher** [comment]
I am aware of the pb. Just trying to enforce good practice!!!
