### ISSUE TITLE
Check Tutorials

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/UWGeodynamics#167]

**Comment by rbeucher** [comment]
➤ Julian Giordani commented:

Which files can I run to help?

**Comment by julesghub** [comment]
With change 44efb32. All tutorials except one initialises and begins the solve loop (note I won't check the output). 

It's the badlands coupling one that fails with 
/opt/venv/lib/python3.7/site-packages/UWGeodynamics/surfaceProcesses.py in _init_model(self)
    122
    123             # Build Mesh
--> 124             self.badlands_model.build_mesh(self._demfile, verbose=False)
    125
    126             self.badlands_model.input.outDir = self.outputDir

AttributeError: 'Model' object has no attribute 'build_mesh'

Using badlands 2.0.15

**Comment by rbeucher** [comment]
Easy fix. I'll do that tomorrow

**Comment by rbeucher** [comment]
Fixed now.
