### ISSUE TITLE
Integral of volume calculation for viscous dissipation

### ISSUE THREAD

**Issue by bknight1** [underworldcode/UWGeodynamics#171]
Hi guys,

I'm trying to calculate the viscous dissipation (VD) in my crustal layer for each output. The values for the VD on each node seem about right, however I can't seem to get the integral over the area to produce a VD value for the crust, with multiple values produced when using the integral function. Any help would be greatly appreciated.

Cheers

```
CrustVD_list   = []
# MantleLVD_list = []
  
# def viscous_dissipation_calc():
### Calculation on swarm
Model.swarmViscousDissipation.data[:] = 2. * GEO.dimensionalise(Model.strainRate_2ndInvariant.evaluate( Model.swarm), 1./u.second) * GEO.dimensionalise(Model.strainRate_2ndInvariant.evaluate( Model.swarm), 1./u.second) * GEO.dimensionalise(Model.viscosityField.evaluate( Model.swarm), u.pascal * u.second)
### Calculation on mesh
#Model.meshViscousDissipation.data[:] = 2. * Model.strainRate_2ndInvariant.evaluate( Model.mesh) * Model.strainRate_2ndInvariant.evaluate( Model.mesh) * Model.viscosityField.evaluate( Model.mesh)
Model.meshViscousDissipation.data[:] = 2. * GEO.dimensionalise(Model.strainRate_2ndInvariant.evaluate( Model.mesh), 1./u.second) * GEO.dimensionalise(Model.strainRate_2ndInvariant.evaluate( Model.mesh), 1./u.second) * GEO.dimensionalise(Model.viscosityField.evaluate( Model.mesh), u.pascal * u.second)



### Value of VD in crust
Crust_VD = Model.meshViscousDissipation.data[(Model.projMaterialField.data[:] > air.index) & (Model.projMaterialField.data[:] < mantleLithosphere.index)]

### Value of VD in mantle lithosphere
# MantleL_VD = Model.meshViscousDissipation.data[(Model.projMaterialField.data[:] == mantleLithosphere.index)]

CrustVD_integral = Model.mesh.integrate(Crust_VD) 

CrustVD_list.append(CrustVD_integral)
```

**Comment by rbeucher** [comment]
I’ll have a look. Might take a couple of days though…

**Comment by bknight1** [comment]
Thanks @rbeucher, something I've wanted to try implement for a while. I can also use the Paraview tool to integrate over the area but would be quicker if it could be done during model runs rather than in post processing.

**Comment by bknight1** [comment]
Also forgot to add that I can save the new swarm/mesh variables as h5 but can't get the xmf output to work. I've had a look through the docs but can't seem to find anything and I can't get the old approach from UW working, I get the following error:

```
ValueErrorTraceback (most recent call last)
<ipython-input-90-ec0b72008da9> in <module>
      2 file_prefix = os.path.join(directory, 'swarmStrainRateInv-%s' % Model.checkpointID)
      3 handle = Model.swarmStrainRateInv.save('%s.h5' % file_prefix)
----> 4 Model.swarmStrainRateInv.xdmf('%s.xdmf' % file_prefix, handle, 'swarmStrainRateInv', Model.swarm, 'swarm')

/usr/local/underworld2/lib/underworld/swarm/_swarmvariable.py in xdmf(self, filename, varSavedData, varname, swarmSavedData, swarmname, modeltime)
    539                 raise ValueError("'filename' must be of type str")
    540             if not isinstance(swarmSavedData, uw.utils.SavedFileData ):
--> 541                 raise ValueError("'swarmSavedData' must be of type SavedFileData")
    542             if not isinstance(varSavedData, uw.utils.SavedFileData ):
    543                 raise ValueError("'varSavedData' must be of type SavedFileData")

ValueError: 'swarmSavedData' must be of type SavedFileData
```

**Comment by rbeucher** [comment]
@julesghub can you have a look at this. 
@bknight1 I don't think you can use the integrate method on an internal domain. That only works for the walls... @julesghub  correct me if I am wrong.
You need to sum the elements in the domain you are interested in...

**Comment by julesghub** [comment]
Yep I can look at it. @bknight1 do you have an example you can point me too. Perhaps a github repo? private if needed.

**Comment by bknight1** [comment]
Thanks @rbeucher and @julesghub 

I've just sent you an invite @julesghub, would it be easier to discuss over email?

**Comment by bknight1** [comment]
> Also forgot to add that I can save the new swarm/mesh variables as h5 but can't get the xmf output to work. I've had a look through the docs but can't seem to find anything and I can't get the old approach from UW working, I get the following error:
> 
> ```
> ValueErrorTraceback (most recent call last)
> <ipython-input-90-ec0b72008da9> in <module>
>       2 file_prefix = os.path.join(directory, 'swarmStrainRateInv-%s' % Model.checkpointID)
>       3 handle = Model.swarmStrainRateInv.save('%s.h5' % file_prefix)
> ----> 4 Model.swarmStrainRateInv.xdmf('%s.xdmf' % file_prefix, handle, 'swarmStrainRateInv', Model.swarm, 'swarm')
> 
> /usr/local/underworld2/lib/underworld/swarm/_swarmvariable.py in xdmf(self, filename, varSavedData, varname, swarmSavedData, swarmname, modeltime)
>     539                 raise ValueError("'filename' must be of type str")
>     540             if not isinstance(swarmSavedData, uw.utils.SavedFileData ):
> --> 541                 raise ValueError("'swarmSavedData' must be of type SavedFileData")
>     542             if not isinstance(varSavedData, uw.utils.SavedFileData ):
>     543                 raise ValueError("'varSavedData' must be of type SavedFileData")
> 
> ValueError: 'swarmSavedData' must be of type SavedFileData
> ```

Also managed to work out how to add mesh variables to the xmf file, however the swarm variables are not produced.

Add variables:
```
swarmStrainRateInv = Model.add_swarm_variable(name='SR_swarm', count=1)

viscositySwarm = Model.add_swarm_variable(name='Viscosity_swarm', count=1)

swarmViscousDissipation = Model.add_swarm_variable(name='VD_swarm', count=1)

meshViscousDissipation = Model.add_mesh_variable(name='VD_mesh', nodeDofCount=1 )
```

and append them to the output:
```
GEO.rcParams["default.outputs"].append("SR_swarm")
GEO.rcParams["default.outputs"].append("VD_swarm")
GEO.rcParams["default.outputs"].append("VD_mesh")
GEO.rcParams["default.outputs"].append("Viscosity_swarm")
```

However only the mesh variable (VD_mesh) is added to the output. Any ideas?

**Comment by julesghub** [comment]
Hi @bknight1, I have push something to the repo you shared with me. See how you go with the changes.

**Comment by bknight1** [comment]
Awesome, thanks for that @julesghub!
I'll close this for now

**Comment by julesghub** [comment]
ok sweet, also re: the swarm output issue. A work around is to define the swarm_variable as `restart_variable`. This is not ideal but I have used it before.
`svar = Model.add_swarm_variable(name='swarm_var', restart_variable=True, count=1)`

**Comment by bknight1** [comment]
Thanks @julesghub, that works for new swarm variables. Is there a workaround for ones already assigned by UWGeo (e.g. Model.viscosityField)
