### ISSUE TITLE
Readthedocs documentation site error

### ISSUE THREAD

**Issue by plovely** [underworldcode/UWGeodynamics#178]
I cannot access the User Guide from ReadTheDocs.   The links from the main documentation page takes me here:
https://uwgeodynamics.readthedocs.io/en/latest/User%20Guide.html
![image](https://user-images.githubusercontent.com/30320218/78080260-7c2d5380-7373-11ea-8d88-31131cfc3946.png)

Thanks,
Pete

**Comment by rbeucher** [comment]
Hi Peter,

I have fixed "latest".
Try again after refreshing your cache.

cheers

Romain

**Comment by plovely** [comment]
Good now.  Thanks,  Romain!
