### ISSUE TITLE
Disruption of record of Lagrangian Particules attributes at model restart

### ISSUE THREAD

**Issue by BenedicteCT** [underworldcode/UWGeodynamics#179]
I have defined a Lagrangian Grid with a set of passive tracers for which I have chosen to record a few attributes (e.g. temperature, pressure, viscosity...). The record of these attributes does not restart when I perform a model restart.

In the two attached files LagGridTimeStep1214 is the last time step for which the record is complete. LagGridTimeStep1215 contains only x,y infos about the passive tracers and not the other attributes (temperature, pressure, viscosity...). 

How can I continue the record of all attributes of the passive markers through the restart ?

[LagGridTimeStep1214.pdf](https://github.com/underworldcode/UWGeodynamics/files/4435943/LagGridTimeStep1214.pdf)
[LagGridTimeStep1215.pdf](https://github.com/underworldcode/UWGeodynamics/files/4435944/LagGridTimeStep1215.pdf)

**Comment by rbeucher** [comment]
OK @BenedicteCT . I will check that and make the changes

**Comment by rbeucher** [comment]
This should be fixed in v2.9.5
