### ISSUE TITLE
How to retrieve dt from main simulator loop for updating boundary conditions

### ISSUE THREAD

**Issue by HanyMKhalil** [underworldcode/UWGeodynamics#181]
Dear Romain, so basically I am using UWGeodynamics to model rifting, and I want to implement rotational boundary conditions. I wrote a rotation function that takes rotation pole coordinates, along with Model.x and Model.y and the angle and gives me new positions of the points after specific (dt). To update the velocity boundary conditions I need the following:
 
a) retrieve the dt from the solver and let the code run in a loop with updated dt every time step (I guess it will be sth like: total time of that step+dt)
 
using dt in a function will do…?  Or do you specify something like Model.dT, Model.currentTime…?
 
b) Where are the boundary nodes coordinates accessible
 
mesh.data…?
 
c) last thing the Model.mesh.advection does not work in y direction only in x
 
Looking at Udw2.0 it seems as straight as a adding one line
Is there any way to add it?
 
All these steps could be easily implemented in Underworld 2.0
but we wouldn’t like to give up the rheology, scaling and other implementations in UWGeodynamics, also I am totally new to Underworld.
 
thank you so much

**Comment by bknight1** [comment]
a) Model._dt gives the timestep
b) Model.mesh.specialSets gives you all the sidewall options, then can find the one you want (e.g. Model.mesh.specialSets['Left_VertexSet'] will give you the left wall.
c) Model.mesh_advector(axis=0) can be used to advect the mesh, the axis argument defines the direction of deformation (x=0, y=1, z=2).

**Comment by HanyMKhalil** [comment]
Hi Ben, Thank you so much, I am so happy that its possible to call tilmestep in the loop.

a)But then I have the issue of rerun the whole manuscript with the updated dt without doing it manually? I think its possible in Underworld2 in the solver run loop, but I do not know how this done in UWGeodynamics? any ideas except for restart the model manually. in principle I will update the velocity BC with every dt but how I rerun the model with the updated velocity BC every timestep?

b) great thanks a lot I will try that

c) yes I tried with Model.mesh_advector(axis=1) for example but it says it does not yet implemented. also there is no option to advect the mesh in x and y at same time

**Comment by bknight1** [comment]
You can use Model.pre_solve_functions for pre solve or Model.post_solve_functions for post solve to update the BC, you just have to pass a function to it.

```
def UpdateVelocity():

    velocity = 19*(1-.07)**float(Model.time/1e6/u.year)
    velocity = np.where(velocity >= 10, 10, velocity)
    velocity = np.where(velocity <= 2, 2, velocity)
    conv_vel = velocity * (u.centimeter / u.year)

    conditionsA = [(Model.y < GEO.nd(0. * u.kilometre), GEO.nd(conv_vel)),
                   (True, GEO.nd(conv_vel) + Model.y * (GEO.nd((-2. * conv_vel) / GEO.nd(Sticky_air * u.kilometer))))]


    Left_wall_vel_changed = fn.branching.conditional(conditionsA)


    Model.set_velocityBCs(left = [Left_wall_vel_changed, None],
                      right=[0., None],
                      top = [None, 0.])
```
then

`Model.pre_solve_functions["A"] = UpdateVelocity`

to update the side wall velocity pre solve.

Not sure about the mesh advection as I haven't tried it, hopefully someone else can help. But if you can do it in UW then you can use the same code in UWG.

**Comment by HanyMKhalil** [comment]
Thanks Ben so much, I will try these using my updated velocity function.

Yes I hope Romain could help with the mesh advection so we can show clearly how the mesh moves

**Comment by rbeucher** [comment]
Hi @HanyMKhalil ,

Why do you need to deform the mesh. That will make the model significantly harder to solve and potentially lead to issues after a few timesteps... deforming in both x and y is going to be error prone I think. If I understand correctly what you are trying to do, the mesh will not deform homogeneously... 

R

**Comment by HanyMKhalil** [comment]
Hi @rbeucher Thanks a lot I just though it would be better to show how it deforms, but yes you are right it will cause instability problem.
Ok I will proceed with Ben suggestions and see how it goes
