### ISSUE TITLE
 appear error when I pull the latest version by docker

### ISSUE THREAD

**Issue by brightson999** [underworldcode/UWGeodynamics#183]
I  pull the latest version by docker, but show me a error with unauthorized: authentication required. and I am sure I login in docker.

**Comment by julesghub** [comment]
I believe you're encountering the jupyter notebook server authentication not docker. 

The authentication key should be in the log available from kitematic, eg. see the red highlighted bit, ![authentication](https://user-images.githubusercontent.com/13825704/80929166-18bc9880-8ded-11ea-8d7f-befc0efd4333.png)
from this message we can see the key is 2159137726adf8f8af33b50ba589389fb818000ba6646763.
You're key will be different from the one above. Please try it.

**Comment by rbeucher** [comment]
Did that solve your issue @brightson999 ? Please close the issue or let us know if there is still a pb.

**Comment by brightson999** [comment]
Sorry for the delay.
recently, I try to fix this problem according to your suggestion several times. but don't know why it is working now using the same operation today. perhaps it's just the Internet problem. I will close this issue for now.

thank you so much again.
best wishes.
