### ISSUE TITLE
zOnly movement of particles

### ISSUE THREAD

**Issue by bknight1** [underworldcode/UWGeodynamics#187]
Hi guys,

Sorry to keep bringing up issues with the surface/surface processes, but I've found that that zOnly surface tracers isn't working as expected. 

I've attached a screen shot, showing after 1 TS both zOnly (white) and a normal surface, with both x and z movement (green). You can see the white surface (zOnly) moves into the air layer, whilst the green layer tracks the original surface.

![zOnly_example](https://user-images.githubusercontent.com/55677727/82535660-8b1dce80-9b8a-11ea-800e-cf53663be089.png)

Cheers

**Comment by rbeucher** [comment]
Can you show us the same figure with the grid as well?

**Comment by bknight1** [comment]
Here's two, the first the same as above (0.15Myr):

![zOnly-1TS](https://user-images.githubusercontent.com/55677727/82536635-19468480-9b8c-11ea-8608-7ba131c723ff.png)

And after 1.65 Myr:

![zOnly-11TS](https://user-images.githubusercontent.com/55677727/82536743-485cf600-9b8c-11ea-8775-c20788dd8f11.png)

**Comment by rbeucher** [comment]
I see. I suspect that's an effect of the grid resolution. Once the points are in the "air" things get a lot worse. Let me think about this. 
The spline is probably a better approach for the kind of model you are running.

**Comment by bknight1** [comment]
Thanks @rbeucher 

I'll have a look into the spline approach and see how it goes, many thanks

**Comment by bknight1** [comment]
Managed to chuck something together that works, heres the surface tracking now after 1.65 Myr. 

Happy to share the code if needed.

![spline_surface_tracking](https://user-images.githubusercontent.com/55677727/82618044-41c69100-9c15-11ea-857b-3bd6f266b62d.png)

Cheers

**Comment by rbeucher** [comment]
Closing this for now. Feel free to reopen.
