### ISSUE TITLE
problem with the viscoelastic half-space example!

### ISSUE THREAD

**Issue by totaibi01** [underworldcode/UWGeodynamics#189]
Hello everyone,

I could not get the same results by running the Loading and unloading of a viscoelastic half-space example, particularly the last figure!

Here is the example in the UWGeodynamics/examples folder, GitHub:
https://github.com/underworldcode/UWGeodynamics/blob/master/examples/1_08_ViscoElasticHalfSpace.ipynb

Can someone update me with what is missing in this example to reproduce the last figure?

Thanks,
Thamer

**Comment by julesghub** [comment]
@totaibi01, I have updated the model to work reasonably. The update was made on the development branch (2.10-pre_release). but it also works with the previous release UWGeodynamics-v2.8.5.
The change @ f9d4fe9

There were 2 problems: 
1. The numerical timestep size was too large for the model once "small" forces were occurring. This lead to overshoots in time. By capping the timestep to a 100th of the relax time the overshoots went away. 
This model, with decreased values of mu (shear modulus), becomes very difficult for underworld's viscoelastic implementation to resolve without the need to cap the timestep.

2. The passive trace implementation had a bug, causing no data to be shown. 
Now it records. (You can get closer to the analytical solution using higher values for the shear modulus)
![image](https://user-images.githubusercontent.com/13825704/86245019-32f7d480-bbec-11ea-8304-011ca959bb29.png)

**Comment by julesghub** [comment]
I'll close the ticket for now, but feel free to comment more if you have questions/issues. Thanks again for raising the bug.
