### ISSUE TITLE
Dirichlet temperature boundary conditions and thin material layers

### ISSUE THREAD

**Issue by plovely** [underworldcode/UWGeodynamics#196]
Hi Romain and Julian,

I hope you are both well.

When Dirichlet temperature boundary conditions are prescribed by material, e.g.
![image](https://user-images.githubusercontent.com/30320218/90895210-67d00e80-e387-11ea-8dd5-2bac00069b7e.png)
and thin layers such as sticky air and water are present, near surface temperatures become very imprecise because the Dirichlet BC appears to be prescribed at mesh nodes only if all adjacent cells are populated with swarm particles of a single material.  Hence, the Dirichlet BC is not prescribed if adjacent cells are populated by a combination of air, sticky air & water, all of which have prescribed a constant temperature (273K.15 K).

The below image shows an example.  The swarm is colored by material (annotated), the mesh is shown in grey (~1km cells), green points are particle tracers at the rock-air (or rock-water) interface, and black contours are temperature (20 K interval, starting at 274 K).  Temperatures at the rock-air (or rock-water) interface are 40-80 K warmer than they should be.  The Dirichlet temperature BC is prescribed at a few grid nodes in the water layer indicated by magenta arrows, but otherwise is prescribed only above the air-water (or air-stickyAir) interface.  

![image](https://user-images.githubusercontent.com/30320218/90898280-052d4180-e38c-11ea-9024-8b935a913b41.png)

I realize the particle-in-cell implementation will not enforce the dirichlet BC directly at the rock-air interface (it should be 1-2 grid nodes above due to material interpolation, making the rock-air interface 20-40 K warmer than it should be) but this issue with thin layers near surface can exacerbate the problem significantly.

Thanks, Pete

**Comment by rbeucher** [comment]
Hi Peter,

Thanks for your message. Yes it is a known issue. I think that specifying the Dirichlet condition based on materials as only a limited range of application. I have been working on a Free surface implementation (not finished). That might help what you are trying to do...

I'll keep you posted.

R

**Comment by julesghub** [comment]
The Dirichlet BC based on materials is weak if layers are around 2-3 elements in width (and broken if <1 element width).
Can you increase the vertical resolution of the mesh? You could use either a deforming mesh setup or just a higher number of elements.
In either case, large deformations of the thin layers will probably lead to this problem reoccurring after evolution of the model.

**Comment by plovely** [comment]
Romain, Julian,
Thank you.  Yes, increasing mesh resolution should help; I'd been trying to avoid that due to computational cost.  Please do keep me posted regarding the free surface implementation.
Peter
