### ISSUE TITLE
Passive tracers in 3D

### ISSUE THREAD

**Issue by HanyMKhalil** [underworldcode/UWGeodynamics#199]
I just has a small issue with passive tracers: 
In my code I wrote it like this:

import numpy as np
npoints = 1000 # This is the number of points used to define the surface
coords = np.ndarray((npoints, 3))
coords[:, 0] = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
coords[:, 1] = 0.
surface_tracers = Model.add_passive_tracers(name="Surface", vertices=coords)

However it creates only lines not surfaces.
In older versions of UWgeo I used to write it like this and works fine:

npoints = 1024
xp = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
yp = np.linspace(GEO.nd(Model.minCoord[1]), GEO.nd(Model.maxCoord[1]), npoints)

xp, yp = np.meshgrid(xp, yp)
xp = xp.flatten()
yp = yp.flatten()
zp = np.zeros(xp.shape)

surface_tracers = Model.add_passive_tracers(name="Surface", vertices=[xp, yp, zp+GEO.nd(uppercrust.top)])
moho_tracers = Model.add_passive_tracers(name="Moho", vertices=[xp, yp, zp+GEO.nd(lowercrust.bottom)])

any suggestions how I can alter the first code to create a surface with numpy?

**Comment by HanyMKhalil** [comment]
Sorry my code is like:

#passive tracers

npoints = 256 # This is the number of points used to define the surface
coords = np.ndarray((npoints, 3))

coords[:, 0] = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
coords[:, 1] = np.linspace(GEO.nd(Model.minCoord[1]), GEO.nd(Model.maxCoord[1]), npoints)
coords[:, 2] = GEO.nd(0.*u.km)

surface_tracers = Model.add_passive_tracers(name="Surface", vertices=coords)

coords[:, 2] = GEO.nd(-20.*u.km)
BD_tracers = Model.add_passive_tracers(name="BD", vertices=coords)


coords[:, 2] = GEO.nd(-35.*u.km)
moho_tracers = Model.add_passive_tracers(name="Moho", vertices=coords)


coords[:, 2] = GEO.nd(-90.*u.km)
litho_tracers = Model.add_passive_tracers(name="Litho", vertices=coords)

**Comment by julesghub** [comment]
@HanyMKhalil , in the "new code" you're missing the  `np.meshgrid()` to construct the full x,y,z vectors, you used it in the "old code" example.

**Comment by HanyMKhalil** [comment]
Thanks Jules, so should I added it in this way?


coords = np.meshgrid(coords[:, 0], coords[:, 1])
coords[:, 0] = coords[:, 0].flatten()
coords[:, 1] = coords[:, 1].flatten()
coords[:, 2] = np.zeros(coords[:, 0].shape)

but I also get this error:

ValueError: The 'coordinateArray' must have shape n*dim, where 'n' is the
                              number of particles to add, and 'dim' is the dimensionality of
                              the supporting mesh (3).

**Comment by julesghub** [comment]
@HanyMKhalil, the error suggests the `coords` array is the wrong shape, it must be the same dimensionality as your model. The model is 3D right? Then `coords` must be 3D, it appears 2D above.

Check the shape of what you give as the `vertices` by running
`coords.shape`

**Comment by HanyMKhalil** [comment]
yes I adjust it:

npoints = 256 # This is the number of points used to define the surface
coords = np.ndarray((npoints, 3))

coords[:, 0] = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
coords[:, 1] = np.linspace(GEO.nd(Model.minCoord[1]), GEO.nd(Model.maxCoord[1]), npoints)
# coords[:, 2] = GEO.nd(0.*u.km)


coords = np.meshgrid(coords[:, 0], coords[:, 1])
coords[:, 0] = coords[:, 0].flatten()
coords[:, 1] = coords[:, 1].flatten()
coords[:, 2] = np.zeros(coords[:, 0].shape)

coords[:, 2] += GEO.nd(6.*u.km)
surface_tracers = Model.add_passive_tracers(name="Surface", vertices=coords)


but I got that error:
TypeErrorTraceback (most recent call last)
<ipython-input-16-e029b02d8645> in <module>
      8 
      9 coords = np.meshgrid(coords[:, 0], coords[:, 1])
---> 10 coords[:, 0] = coords[:, 0].flatten()
     11 coords[:, 1] = coords[:, 1].flatten()
     12 coords[:, 2] = np.zeros(coords[:, 0].shape)

TypeError: list indices must be integers or slices, not tuple

**Comment by julesghub** [comment]
The code is confusing because it's redefining `coords`. Consider using something like
```python
    xx = np.linspace(minX, maxX, numX)
    yy = np.array([GEO.nd(y)])
    zz = np.linspace(minZ, maxZ, numZ)

    xx, yy, zz = np.meshgrid(xx,yy,zz)
    
    coords = np.ndarray((xx.size, 3))
    coords[:,0] = xx.ravel()
    coords[:,1] = yy.ravel()
    coords[:,2] = zz.ravel()
       
    tracers = Model.add_passive_tracers(name, vertices = coords)
```
Check the shape and values of each numpy variable before using it.

**Comment by HanyMKhalil** [comment]
Hi Julie I tried that but gives same error. I also tried the code in this way:

npoints = 256
xx = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
yy = np.linspace(GEO.nd(Model.minCoord[1]), GEO.nd(Model.maxCoord[1]), npoints)
zz = np.zeros(xx.shape)

xx, yy, zz = np.meshgrid(xx,yy,zz)
    
coords = np.ndarray((xx.size, 3))
coords[:,0] = xx.ravel()
coords[:,1] = yy.ravel()
coords[:,2] = zz.ravel()
       
zz = np.array([GEO.nd(0.*u.km)])
surface_tracers = Model.add_passive_tracers(name="Surface", vertices=coords)

zz = np.array([GEO.nd(-35.*u.km)])
Moho_tracers = Model.add_passive_tracers(name="Moho", vertices=coords)


I checked the shape and size of every array, and I think I should create a zeros array for z which is the depth but yet the error persists??


ValueErrorTraceback (most recent call last)
<ipython-input-17-faad5e4df025> in <module>
     12 
     13 zz = np.array([GEO.nd(0.*u.km)])
---> 14 surface_tracers = Model.add_passive_tracers(name="Surface", vertices=coords)

/usr/local/lib/python3.5/dist-packages/UWGeodynamics/_model.py in add_passive_tracers(self, name, vertices, particleEscape, centroids, zOnly)
   1836                                      particleEscape=particleEscape,
   1837                                      zOnly=zOnly)
-> 1838             tracers.add_particles_with_coordinates(vertices)
   1839 
   1840         else:

/usr/local/lib/python3.5/dist-packages/UWGeodynamics/_utils.py in add_particles_with_coordinates(self, vertices, **kwargs)
     94         vals = super(PassiveTracers,
     95                      self).add_particles_with_coordinates(points,
---> 96                                                           **kwargs)
     97         self.advector = uw.systems.SwarmAdvector(
     98             swarm=self,

/usr/local/underworld2/lib/underworld/swarm/_swarm.py in add_particles_with_coordinates(self, coordinatesArray)
    205             raise ValueError("""The 'coordinateArray' must have shape n*dim, where 'n' is the
    206                               number of particles to add, and 'dim' is the dimensionality of
--> 207                               the supporting mesh ({}).""".format(self.mesh.dim) )
    208         retarr = self._cself.GeneralSwarm_AddParticlesFromCoordArray( coordinatesArray )
    209         # lets realloc swarm now

ValueError: The 'coordinateArray' must have shape n*dim, where 'n' is the
                              number of particles to add, and 'dim' is the dimensionality of
                              the supporting mesh (3).

**Comment by jmansour** [comment]
@HanyMKhalil  a few questions:

1. How many particles are you expecting your surface passive swarm to have? 
2. What is the shape of your `coords` array? 
3. What shape should `coords` have?

**Comment by julesghub** [comment]
@HanyMKhalil, also what version of the code are you using?

**Comment by HanyMKhalil** [comment]
for particles around 32

My coordinate shape just for testing model:
Model = GEO.Model(elementRes=(16, 32, 6), 
                  minCoord=(-16. * u.kilometer,   0. * u.kilometer, 0. * u.kilometer), 
                  maxCoord=(16. * u.kilometer,  64. * u.kilometer, 6. * u.kilometer),  
                  gravity=(0.0, 0.0, -10.0 * u.meter / u.second**2))

I am using the most recent version where it requires an np array for the passive swarms

**Comment by HanyMKhalil** [comment]
the whole surface should be around 32x64 but for simplicity I create it as 32x32

**Comment by jmansour** [comment]
@HanyMKhalil where does `32` come from?  I'm seeing that you've specified `npoints=256`, so therefore shouldn't your swarm need `256*256=65536` particles?

Also i'm after the array shape. So what is `coords.shape`?

**Comment by HanyMKhalil** [comment]
Yes, I just put the number of passive swarm points to be 256 but I though it does not matter. When I changed it to 32 gives the same error.

The coords.shape should be 16x32 and then I specify that for each depth of z. so I created zeros array for z to fill it later with the depth value I want.

in previous version of UW I used this code which worked fine for me:

npoints = 1024
xp = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
yp = np.linspace(GEO.nd(Model.minCoord[1]), GEO.nd(Model.maxCoord[1]), npoints)

xp, yp = np.meshgrid(xp, yp)
xp = xp.flatten()
yp = yp.flatten()
zp = np.zeros(xp.shape)

surface_tracers = Model.add_passive_tracers(name="Surface", vertices=[xp, yp, zp+GEO.nd(uppercrust.top)])
moho_tracers = Model.add_passive_tracers(name="Moho", vertices=[xp, yp, zp+GEO.nd(lowercrust.bottom)])

**Comment by HanyMKhalil** [comment]
In the recent code of UW Romain add passive tracers in 2D as follow:

import numpy as np

npoints = 1000 # This is the number of points used to define the surface
coords = np.ndarray((npoints, 2))

coords[:, 0] = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
coords[:, 1] = 0.

surface_tracers = Model.add_passive_tracers(name="Surface", vertices=coords)

coords[:, 1] -= GEO.nd(35.*u.km)
moho_tracers = Model.add_passive_tracers(name="Moho", vertices=coords)

But I could not extend it to 3D

**Comment by julesghub** [comment]
using the `2.10` version I could extend the above to be 3D. See the following.
```python
import numpy as np

npoints = 1000 # This is the number of points used to define the surface

xx = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
yy = 0.
zz = np.linspace(GEO.nd(Model.minCoord[2]), GEO.nd(Model.maxCoord[2]), npoints)

xx,yy,zz = np.meshgrid(xx,yy,zz)
coords = np.ndarray((xx.size, 3))

coords[:,0] = xx.ravel()
coords[:,1] = yy.ravel()
coords[:,2] = zz.ravel()
surface_tracers = Model.add_passive_tracers(name="Surface", vertices=coords)

coords[:, 1] -= GEO.nd(35.*u.km)
moho_tracers = Model.add_passive_tracers(name="Moho", vertices=coords)
```

If this above doesn't help please report the output of :
```python
coords.shape, GEO.__version__
```

**Comment by HanyMKhalil** [comment]
No, it does not work.
ValueError: The 'coordinateArray' must have shape n*dim, where 'n' is the
                              number of particles to add, and 'dim' is the dimensionality of
                              the supporting mesh (3).

output for:
 coords.shape, GEO.__version__ 
>> ((1000000, 3), '2.8.5')

**Comment by HanyMKhalil** [comment]
aha maybe the version is different as I try this on my laptop which has an older version

**Comment by HanyMKhalil** [comment]
I submitted on Gadi the newer version, so this might cause the confusion! I will try it on Cluster

**Comment by HanyMKhalil** [comment]
but shouldn't it work also with older versions like 2.8?

**Comment by julesghub** [comment]
My instruction work for 2.10. It won't work for 2.8 as `add_passive_tracers()` changed at 2.9.

**Comment by julesghub** [comment]
Can you update your laptop to the latest version? You should (well must) run the same version of code on Gadi and your laptop if you're modifying models.

**Comment by HanyMKhalil** [comment]
Yes, I will do that, Thanks Julian so much, I will check that.

**Comment by HanyMKhalil** [comment]
Hi @julesghub @jmansour The passive tracers works perfectly thanks so much, I just have one small question.

Is it possible in UWgeodynamcis to advect the passive tracers only vertically, sot hat no advection in x and y? and also how to interpolate the strain rate on the particles (in this case passive tracers) and save them??

Thanks so much for your help, much appreciate any recommendation ^_^

**Comment by jmansour** [comment]
@rbeucher can fill you in on the `UWGeo` method for advecting vertically only.  I suspect the easiest thing might be to take a copy of the velocity field, set the required axis to zero, and then use that for the advection. 

For the interpolation, you can simply do evaluate using the passive tracer coordinates as an input.  Something like this should work on any recent version of `underworld`.
```python
your_strainrate_object.evaluate(passiveSwarm.data)
```

**Comment by rbeucher** [comment]
Hi @HanyMKhalil ,

We used to have that option but I removed it a few months ago...
You can still do it as @jmansour is suggesting. Maybe create a copy of the velocityField with the x component set to 0. and pass a new advector to the passive tracers,

**Comment by HanyMKhalil** [comment]
@rbeucher thanks Romain,
Is there a possibility that you could give me some line samples to start by. I am just still new and try to get familiar with how to copy and pass the advection. Do I do that when I am constructing the passive tracers before initiate the model??

**Comment by HanyMKhalil** [comment]
@jmansour  @rbeucher any lines could help me to start so that i only advect the passive tracers in z direction only and then save strain rate on it??

**Comment by rbeucher** [comment]
Yes. I'll send you something. Sorry been busy with other things

**Comment by HanyMKhalil** [comment]
Hi all, is 
strainrate_object.evaluate(passiveSwarm.data) should be defined while defining the passive swarms? like before the model initial or after?
I also think there is no advection in y direction only in x and z correct?

**Comment by HanyMKhalil** [comment]
So I followed your advice in order to advect the passive tracers only in z direction so I did it this way, it works fine on my laptop but on Gadi gives me error.

this is my code:

`
npoints = 1024 # This is the number of points used to define the surface

xx = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
yy = np.linspace(GEO.nd(Model.minCoord[1]), GEO.nd(Model.maxCoord[1]), npoints)
zz = 0.

xx,yy,zz = np.meshgrid(xx,yy,zz)
coords = np.ndarray((xx.size, 3))

coords[:,0] = xx.ravel()
coords[:,1] = yy.ravel()
coords[:,2] = zz.ravel()
surface_tracers = Model.add_passive_tracers(name="Surface", vertices=coords)

coords[:,2] = GEO.nd(-10.*u.km)
mid_uppercrust_tracers = Model.add_passive_tracers(name="mid_UC", vertices=coords, advect=False)

coords[:,2] = GEO.nd(-55.*u.km)
mid_mantleLithosphere_tracers = Model.add_passive_tracers(name="mid_LM", vertices=coords, advect=False)

def PassiveTracersLoop():
    ### This gets the tracer velocity
    UC_tracer_velocity = Model.velocityField.evaluate(mid_uppercrust_tracers)
    LM_tracer_velocity = Model.velocityField.evaluate(mid_mantleLithosphere_tracers)
    Model._dt = Model._dt or 0.
    ### advect the particles in the Z direction manually
    mid_uppercrust_tracers.data[:,2] = mid_uppercrust_tracers.data[:,2] + (UC_tracer_velocity[:,2] * Model._dt)
    mid_mantleLithosphere_tracers.data[:,2] = mid_mantleLithosphere_tracers.data[:,2] + (LM_tracer_velocity[:,2] * Model._dt)

    
#we initialize the function
PassiveTracersLoop()

Model.pre_solve_functions["A"] = PassiveTracersLoop
`

this is the error:

An uncaught exception appears to have been raised by all processes. Set the 'UW_ALL_MESSAGES' environment variable to see all messages. Rank 0 message is:Traceback (most recent call last):  File "/home/565/hk2371/q4_2020_jobs/models_4/3D-ortho-0.32v-2km-Gadi-damage0.22.py", line 253, in <module>    PassiveTracersLoop()  File "/home/565/hk2371/q4_2020_jobs/models_4/3D-ortho-0.32v-2km-Gadi-damage0.22.py", line 248, in PassiveTracersLoop    mid_uppercrust_tracers.data[:,2] = mid_uppercrust_tracers.data[:,2] + (UC_tracer_velocity[:,2] * Model._dt)
IndexError: index 2 is out of bounds for axis 1 with size 1

any advice? thank you so much

**Comment by HanyMKhalil** [comment]
@julesghub any advice??

**Comment by jmansour** [comment]
@HanyMKhalil, does this work in serial? 

You might also need to add a check to ensure correct operation on processes that don't have any particles, although I don't believe that this is the issue here as the exception seems to have been raised on all procs.

Something like:

```python

def PassiveTracersLoop():
    Model._dt = Model._dt or 0.

    ### advect the particles in the Z direction manually
    with mid_uppercrust_tracers.deform_swarm():
        if mid_uppercrust_tracers.particleLocalCount > 0:
            UC_tracer_velocity = Model.velocityField.evaluate(mid_uppercrust_tracers)
            mid_uppercrust_tracers.data[:,2] = mid_uppercrust_tracers.data[:,2] + (UC_tracer_velocity[:,2] * Model._dt)

    with mid_mantleLithosphere_tracers.deform_swarm():
        if mid_mantleLithosphere_tracers.particleLocalCount > 0:
            LM_tracer_velocity = Model.velocityField.evaluate(mid_mantleLithosphere_tracers)
            mid_mantleLithosphere_tracers.data[:,2] = mid_mantleLithosphere_tracers.data[:,2] + (LM_tracer_velocity[:,2] * Model._dt)

```
I've also added the `deform_swarm()` context managers that are required any time you move particles (they act to migrate particles across processes at the conclusion of deformation). I assume will also be required for UWGeo @rbeucher?

**Comment by HanyMKhalil** [comment]
Hi John, yes it works perfectly on serial. but it does not work at all on Gadi in parallel!!

Shall I try it on Gadi with the new deform_swarm() ??

**Comment by jmansour** [comment]
If it works in serial without the `deform_swarm()` context managers (which I'm surprised to hear), then I don't think it'd make a difference in parallel.  However, I'm almost certain you will need to make sure there's greater than zero particles, as in those situations the `UC_tracer_velocity` objects will probably not be of compatible shape (which is probably what the error message is saying). 

But I'd suggest you get in the habit of running in parallel locally before you launch on Gadi. It'll be much faster for your debugging process!  Open a terminal and run `mpirun -np 2 python YOURSCRIPT.py` to see if it works with 2 procs, for example.

**Comment by HanyMKhalil** [comment]
I tried it but on terminal but says

*hkha0004@MU00106269X*:*~*$ mpirun -np 2 python
3D-ortho-0.32v-2km-Gadi-test.py

-bash: mpirun: command not found

**Comment by jmansour** [comment]
If you are using Docker, you will have to do this from within the Docker environment.  Although, you can start a terminal from the Jupyter menu and it'll give you basically the same thing.

**Comment by HanyMKhalil** [comment]
Hi John, it seems to work well, I ran it on 16 core with low resolution. I will try on a higher resolution with bigger number of passive tracers to make sure. But yes I do not fully understand the problem

**Comment by HanyMKhalil** [comment]
Hi All, I have tried the loop and it works but the passive tracers does not really deform accurately, here is a picture
<img width="426" alt="Screen Shot 2020-12-17 at 12 12 39 pm" src="https://user-images.githubusercontent.com/53889438/102425411-5b23a480-4061-11eb-93d0-b9ee1f3b16aa.png">

**Comment by HanyMKhalil** [comment]
@jmansour @rbeucher @julesghub  any ideas how I can make it more accurate?

**Comment by jmansour** [comment]
It's impossible for us to tell you what's gone wrong here. 

What result do you get if you advect with whole velocity (as opposed to just the vertical velocity)? 

You might also consider using a simple synthetic velocity configuration to confirm correct behaviour.

**Comment by HanyMKhalil** [comment]
Hi John,
so basically I applied a horizontal velocity of magnitude 1.28 cm/yr, the element size is 64x64 
the white line represents the passive tracers on surface advect in all directions while the yellow line is the passive tracers in the middle of upper crust (so to not get affected by air) with advect in z direction only
<img width="526" alt="Screen Shot 2020-12-17 at 12 54 50 pm" src="https://user-images.githubusercontent.com/53889438/102432612-7ee9e900-4067-11eb-943d-20ef1afc7086.png">

**Comment by HanyMKhalil** [comment]
I guess I understood the tracers advection behaviour, actually they work quite well while the model moves up in initial rifting stages, however when the rift starts to widen in x direction and no more vertical moment, the vertical component of the tracers remains static and that's why this difference happens.

I found also that I can visualise the strain rate by do contouring instead of advecting the tracers in z direction, which works quite well

**Comment by rbeucher** [comment]
Not sure I understand what is going on with the yellow tracers.

**Comment by jmansour** [comment]
Okay, it seems that this is working as it should. Should this ticket be closed @HanyMKhalil ?

**Comment by HanyMKhalil** [comment]
yes sure, thanks all for that ^_^
