### ISSUE TITLE
On restart FSE swarms is not reloaded.

### ISSUE THREAD

**Issue by patrice-rey** [underworldcode/UWGeodynamics#203]
Hi Romain, hope you are doing great. Students from my 3rd-year class have noticed that on restart the FSE swarm and other user-defined swarms (e.g. surface and moho markers) are not reloaded. I have checked and I can confirm that's case. Cheers, Patrice

**Comment by rbeucher** [comment]
Hi @patrice-rey,

Thanks. Can you just confirm the version you are using. I thought we had fixed that for Benedicte. Last time we spoke things were OK. 
Maybe your student can send me an example of what is going wrong. I may have overlooked something.

Romain

**Comment by patrice-rey** [comment]
Hi Romain, we are using 2.10.1-dev and the Tutorial 1.
Cheers
Patrice

**Comment by rbeucher** [comment]
Hi @patrice-rey 

I can't reproduce the issue. It looks fine for me...

![image](https://user-images.githubusercontent.com/3680918/97826560-04167a00-1d16-11eb-92f9-ce350e805baa.png)

**Comment by patrice-rey** [comment]
Yes, the swarms are loaded but they seems to not be updated. 
After a restart the FSE appears while frozen, while the rest of the model carries on. 
I have sent to you a movie and the input script via email.
P.

**Comment by rbeucher** [comment]
OK. The swarms are reloaded. Pb is at checkpoint they are not saved to files..
I'm on it

**Comment by rbeucher** [comment]
Stupid bug... I have found the pb. Adding that to dev and then issuing a patch for master. I will do a 2.10.2 release.

**Comment by patrice-rey** [comment]
Thanks Romain, all bugs are. Cheers
