### ISSUE TITLE
add compensating vertical influx velocities

### ISSUE THREAD

**Issue by CHENMING27** [underworldcode/UWGeodynamics#205]
Hi  @rbeucher 

I want to use UEGeo to Investigate the process of fault formation at mid-ocean ridge. How can I add compensating vertical influx velocities which are constant along the whole upper and lower boundaries are derived from spreading to ensure conservation of model volume?

**Comment by rbeucher** [comment]
You are gonna have to work out the maths. If you define Dirichlet conditions on 3 out of 4 walls you will have conservation of mass as stokes is solving for it.
