### ISSUE TITLE
Unexpected asymmetric results from a simple model

### ISSUE THREAD

**Issue by NengLu** [underworldcode/UWGeodynamics#207]
Hi,
I tried to reproduce the mode case2 in Crameri2012, it has simple geometry and linear rheology settings.
The resolution is the same as the reference 560*340 (2800km*(700+150)km). The boundary condition is set as:
Model.set_velocityBCs(left=[0., None], right=[0., None], bottom=[0.,0.],  top = [None,0.])

The results of the strain rate field and surface topography (like Fig.7 in the reference) should be axisymmetric while they are not. 
Here are the results at 4 Ma:
![image](https://user-images.githubusercontent.com/57476594/99211377-495da000-281c-11eb-825b-2df0257dee89.png)
![image](https://user-images.githubusercontent.com/57476594/99211389-51b5db00-281c-11eb-95d9-b7a9cfd9fffe.png)

I have tried using smaller nonlinear. tolerance and more iteration times for the solver, but the results didn't get much better. 

Any suggestions on how to improve it?

And another question is that the results of Model.lithostatic_pressureField are a little small than the accurate ones. It will cause some errors when applied as the stress boundary condition at the bottom, how to fix it? Thanks!

Reference:
Crameri, F., Schmeling, H., Golabek, G. J., Duretz, T., Orendt, R., Buiter, S. J. H., ... & Tackley, P. J. (2012). A comparison of numerical surface topography calculations in geodynamic modelling: an evaluation of the ‘sticky air’method. Geophysical Journal International, 189(1), 38-54.

**Comment by rbeucher** [comment]
@julesghub can you have a look at this?

**Comment by NengLu** [comment]
Similar issue in underworld2 about the stick air model: https://github.com/underworldcode/underworld2/issues/363  
To fix the problem need good scaling, small time interval for calculation (1-3 ka), and using the direct solver (better without using the penalty method)

**Comment by rbeucher** [comment]
@NengLu , When you have time, please update that thread for documentation.

**Comment by NengLu** [comment]
> @NengLu , When you have time, please update that thread for documentation.

Sure.
More info about the problem. The unexpected asymmetric results can be subject to an instability termed a ‘‘sloshing,” or ‘‘drunken sailor effect” instability (Kaus et al., 2010). All of the approaches to free surface simulations (pseudo-free-surface formulation, 'stick air' approximation, ALE scheme) may cause that.

This instability is arisen from the large density contrast typical at a free surface (surface or air-rock interface), compared with the much smaller internal density contrasts, which severely limits the maximum stable time step for free surface computations (Rose et al., 2017).

It can be suppressed by some methods like _Free surface stabilization approach (FSSA)_ from (Kaus et al., 2010), or some tricks, e.g. adding an extra stick air layer with denser density or gradually and continually changed density (from rock density to air density).

Reference
Kaus, B. J., Mühlhaus, H., & May, D. A. (2010). A stabilization algorithm for geodynamic numerical simulations with a free surface. Physics of the Earth and Planetary Interiors, 181(1-2), 12-20.
Rose, I., Buffett, B., & Heister, T. (2017). Stability and accuracy of free surface time integration in viscous flows. Physics of the Earth and Planetary Interiors, 262, 90-100.

**Comment by rbeucher** [comment]
Thanks @NengLu
