### ISSUE TITLE
Pb in geothermal structure of the crust

### ISSUE THREAD

**Issue by NengLu** [underworldcode/UWGeodynamics#208]
Hello,

Is it necessary to define surface heat flow for maintaining the thermal structure in the crust? 
Take "Tutorial_1_ThermoMechanical_Model " for example, 
the near-surface temperature is too high after initial, T = 103 u.degC at 0 km.
![image](https://user-images.githubusercontent.com/57476594/99212608-95f6aa80-281f-11eb-8321-563bee9a19c6.png)
That can be imporved by fixing the surface nodes to surface temperature:
```
 #Boundary conditions
surface_nodes = GEO.shapes.Layer(top=stickyAir.bottom+resolution/2, bottom=stickyAir.bottom-resolution/2)
Model.set_temperatureBCs(top=293.15 * u.degK, 
                         bottom=1603.15 * u.degK, 
                         materials=[(air, 293.15 * u.degK), (stickyAir, 293.15 * u.degK)],nodeSets=[(surface_nodes,293.15 * u.degK)])
```
T = 32.3 u.degC at 0 km:
![image](https://user-images.githubusercontent.com/57476594/99212614-9ee77c00-281f-11eb-904a-1e778bddd241.png)

Is there any better way to control this?

And how to input the radiogenicHeatProd of the crust in UWG? 
For example, the radiogenic heat production of the crust is 1e-9 w/kg, heat production decay length is 10km, the density of the upper and lower crust is 2700 and 2800 kg/m^3, the thickness of them are both 20km.

The radiogenicHeatProd of UC and LC are 2.7 and 2.8 microwatt/m^3 ? Or taking the average value by considering the decay as 1.53 and 0.22 microwatt/m^3 in UWG? (2.7*(np.exp(-20/10)+1)/2=1.53, 2.8*(np.exp(-40/10)+np.exp(-20/10))/2 =0.22)

**Comment by patrice-rey** [comment]
Hi NengLu
_Is there any better way to control this?_
The one you mention is pretty good. That's the trick I use to fix the temperature in the air layers.

_... how to input the radiogenicHeatProd of the crust in UWG?_
Check Tutorial_1_ThermoMechanical_Model for an example.

An exponential decrease in RHP can be achieved via a function, or a stack of layer of decreasing radiogenic heat production.

Cheers
Patrice

**Comment by NengLu** [comment]
> Hi NengLu
> _Is there any better way to control this?_
> The one you mention is pretty good. That's the trick I use to fix the temperature in the air layers.
> 
> _... how to input the radiogenicHeatProd of the crust in UWG?_
> Check Tutorial_1_ThermoMechanical_Model for an example.
> 
> An exponential decrease in RHP can be achieved via a function, or a stack of layer of decreasing radiogenic heat production.
> 
> Cheers
> Patrice

Hi Patrice,
Thank you, I am going the check the tutorial again.
