### ISSUE TITLE
Gadi install script: hard-coded paths

### ISSUE THREAD

**Issue by benmenadue** [underworldcode/UWGeodynamics#211]
Hi,

In the Gadi install script, you have hard-coded paths to the MPI libraries. Moreover, these are to the internal paths that may change over time:
https://github.com/underworldcode/UWGeodynamics/blob/e99e225d4b149497827e09d14b3f4df5822b380a/docs/nci_gadi/install_on_gadi.sh#L21

A much better solution is to load the appropriate `openmpi` module and use the `$OPENMPI_ROOT` environment variable that it sets. Or even better, don't `LD_PRELOAD` the MPI libraries and let the linker encode the correct location at build time.

Failing those, at least use `/apps/openmpi/<version>` rather than `/apps/openmpi-mofed...` as otherwise your builds will then break as soon as a MOFED or PBS update requires us to rebuild the MPI libraries (e.g. moving to MOFED 5.1, which we were planning on doing in a downtime at some point in the near future).

Cheers,
Ben

**Comment by rbeucher** [comment]
Thanks @benmenadue.
Will use that!

**Comment by rbeucher** [comment]
@julesghub  can you change the script please?

**Comment by julesghub** [comment]
Yep, can look into it
