### ISSUE TITLE
ModuleNotFoundError: No module named 'glucifer'

### ISSUE THREAD

**Issue by peanutchun** [underworldcode/UWGeodynamics#217]
I install the docker software on my ubuntu 20.04, and run the jupyter notebook sucessfully follow the install guide https://uwgeodynamics.readthedocs.io/en/latest/Installation.html.

The environment:
- underworld           2.10.0b0
- UWGeodynamics        2.10.2
- REPOSITORY                     TAG       IMAGE ID       CREATED       SIZE
- underworldcode/uwgeodynamics   latest    5ecbd01ee8f3   7 weeks ago   2.53GB 

And when I write the following code, something wrong

```
import UWGeodynamics as GEO
import glucifer
```

the error message just like this
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d33b2dc30eb8> in <module>
----> 1 import glucifer

ModuleNotFoundError: No module named 'glucifer'
```

**Comment by NengLu** [comment]
Hi peanutchun,
The module "glucifer" has been changed into "UWGeodynamics.visualisation", which is the same as _glucifer_ for visualisation, you can import it as:
`from UWGeodynamics import visualisation as vis`

**Comment by peanutchun** [comment]
Thank you so much

**Comment by peanutchun** [comment]
Thank you so much
