### ISSUE TITLE
Problem in using LecodeIsostasy as bottom boundary condition in convergence or subduction case

### ISSUE THREAD

**Issue by NengLu** [underworldcode/UWGeodynamics#221]
Hi guys,
There is a problem in using lecodeisostasy as the bottom boundary condition when another kind of material deforms and touches the bottom. The bottom material must only be the material set at the very beginning (reference_mat). This needs to be enhanced to handle this situation.

Take a 2D convergence model for example, the velocity boundary condition is set as:
```
Model.set_velocityBCs(left=[velocity,None], right=[0., None],  
                      bottom=GEO.LecodeIsostasy(reference_mat=ma, average=True))
```

The model runs several steps then breaks when deforms like below, another material (lithospheric mantle here, the grey one) touch the bottom (the bottom material is asthenospheric mantle here which is red):
![image](https://user-images.githubusercontent.com/57476594/106082709-49a8de80-616f-11eb-823c-5e0abc4b5c38.png)

And shows the warnings:
/opt/venv/lib/python3.7/site-packages/UWGeodynamics/LecodeIsostasy/LecodeIsostasy.py:141: RuntimeWarning: divide by zero encountered in true_divide
  basal_velocities = -1.0 * botMeanDensities * sep_velocities_nodes / botMeanDensities0
/opt/venv/lib/python3.7/site-packages/underworld/systems/_bsscr.py:482: UserWarning: A PETSc error has been encountered during the solve. Solution fields are possibly erroneous.

**Comment by patrice-rey** [comment]
Hi NengLu, if you are lucky your experiment could work by setting the reference_mat not to the red material but the blue material above. This trick as worked in some of my experiment.  Alternatively, make your box deeper.

**Comment by patrice-rey** [comment]
... there is always a way ... you can setup a phase change to transform the blue material into the red material before it touches the base of the box.

**Comment by NengLu** [comment]
> ... there is always a way ... you can setup a phase change to transform the blue material into the red material before it touches the base of the box.

Hi Patrice,
Thank you for your tips. But the reference_mat setting trick doesn't work for my case. 
The phase change worths a shot, going to try that, thanks!
