### ISSUE TITLE
Residual value is 'nan' during solver iterations

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/UWGeodynamics#228]
Hi,
I am trying reproduce OzBench etal 2008 models in 3D with viscoplastic rheology in the subducting plate crust. While running the model, residual value during each iteration is '-nan'. I am not sure what cause this issue. Any suggestions or help? I am attaching the python script. Thanks.
[subduction_3d_var_slab_dep.py.txt](https://github.com/underworldcode/UWGeodynamics/files/6115844/subduction_3d_var_slab_dep.py.txt)

**Comment by Peigen-L** [comment]
I think your script missed the scaling factors in the very beginning.

**Comment by gthyagi** [comment]
@Peigen-L Thanks now it seems working. In general, I am not very comfortable in using UWGeodynamics and everything happens under the hood. I created the same model in the underworld on the same day and it worked perfectly.
