### ISSUE TITLE
Version 2.10.5

### ISSUE THREAD

**Issue by patrice-rey** [underworldcode/UWGeodynamics#229]
Hello Romain or Julian

In my pbs I have replaced "source /scratch/q97/Underworld/UWGeodynamics_2.10.sh" by
"source /scratch/q97/codes/install_on_gadi.sh" in order to access the new version UWGeo 2.10.5.

On well tested 2D model I've got this warnings on Gadi:

/scratch/q97/codes/UWGeodynamics_2.10.5/lib/python3.8/site-packages/UWGeodynamics/_model.py:1524: UserWarning: You have not passed anything to the temperature argument. The temperature field will not be initialised
  warnings.warn("You have not passed anything to the temperature argument. The temperature field will not be initialised")
/scratch/q97/codes/UWGeodynamics_2.10.5/lib/python3.8/site-packages/UWGeodynamics/_model.py:1528: UserWarning: You have not passed anything to the pressure argument. The pressure field will not be initialised
  warnings.warn("You have not passed anything to the pressure argument. The pressure field will not be initialised")

… and UWGeo stops.

Any insights?
Cheers
Patrice

**Comment by julesghub** [comment]
The warnings above were only made in `2.10.5` UWGeo release. The warnings occur when you call `init_model()` in the UWGeo script _without_ arguments `temperature` and `pressure`.
Can you replace the `init_model()` line with this line:
`Model.init_model(temperature="steady-state", pressure="lithostatic")`

does that change things?

PS: have you run the model with `2.10.5` on your local machine?

**Comment by patrice-rey** [comment]
Thanks of the help Julian.

Yes, with  Model.init_model(temperature="steady-state", pressure="lithostatic”) the warning is gone.

Now I bumped into another issue …


An uncaught exception appears to have been raised by all processes. Set the 'UW_ALL_MESSAGES' environment variable to see all messages. Rank 0 message is:
Traceback (most recent call last):
  File "./L2_Fst7Ext.py", line 582, in <module>
    Model.run_for(80100000 * u.years, checkpoint_interval=100000. * u.year)#, restartStep=1620, restartDir="L1_Int7Ext")
  File "/scratch/q97/codes/UWGeodynamics_2.10.5/lib/python3.8/site-packages/UWGeodynamics/_model.py", line 1599, in run_for
    checkpointer = _CheckpointFunction(
  File "/scratch/q97/codes/UWGeodynamics_2.10.5/lib/python3.8/site-packages/UWGeodynamics/_model.py", line 2321, in __init__
    self.checkpoint_all()
  File "/scratch/q97/codes/UWGeodynamics_2.10.5/lib/python3.8/site-packages/UWGeodynamics/_model.py", line 2400, in checkpoint_all
    self.checkpoint_fields(variables, checkpointID, time, outputDir)
  File "/scratch/q97/codes/UWGeodynamics_2.10.5/lib/python3.8/site-packages/UWGeodynamics/_model.py", line 2442, in checkpoint_fields
    mH = Model.mesh.save('%s.h5' % mesh_prefix,
  File "/scratch/q97/codes/UWGeodynamics_2.10.5/lib/python3.8/site-packages/underworld/mesh/_mesh.py", line 585, in save
    dset[self.data_nodegId[0:local],:] = self.data[0:local] * fact
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/scratch/q97/codes/UWGeodynamics_2.10.5/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 910, in __setitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/scratch/q97/codes/UWGeodynamics_2.10.5/lib/python3.8/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 181, in h5py._selector.Selector.apply_args
TypeError: Only 1D arrays allowed for fancy indexing
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 7 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.






It looks like a few things has changed in 2.10.5 to the point that input script that worked ok on previous version needs to be modified somehow.


PS: have you run the model with 2.10.5 on your local machine?

No.

Tomorrow is a full day for me, and then I take students in the field on Friday. I’ll return next Tuesday. So I won’t be able to run anything until next week.

Cheers

Patrice

Patrice Rey
***@***.******@***.***>
Dr Patrice Rey
School of Geosciences
Earthbyte Research Group
ARC-ITRH Basin Genesis Hub

Associate Head Education Geosciences
Elected Fellow Geological Society of America
Editorial board of EGU - Solid Earth
Editorial board of Frontiers in Earth Science - Structural Geology and Tectonics

Tel: 02 9351 2067
http://www.geosci.usyd.edu.au/users/prey/
***@***.***


On 24 Mar 2021, at 1:48 pm, Julian Giordani ***@***.******@***.***>> wrote:



The warnings above were only made in 2.10.5 UWGeo release. The warnings occur when you call init_model() in the UWGeo script without arguments temperature and pressure.
Can you replace the init_model() line with this line:
Model.init_model(temperature="steady-state", pressure="lithostatic")

does that change things?

PS: have you run the model with 2.10.5 on your local machine?

**Comment by jdpmoore** [comment]
Previously UWGeo used to automatically solve for the steady state temperature. This should be added to the documentation on readthedocs as a breaking change from previous versions of UWGeodynamics as it took me a while to figure it out. I came here today to flag it as an issue then found it was already an open issue.
