### ISSUE TITLE
Yield stress in 3D based on Drucker-Prager criterion

### ISSUE THREAD

**Issue by alireza-bahadori** [underworldcode/UWGeodynamics#231]
Hi everyone,

It seems to me that there is a typo in the formula for calculating the yield stress in 3D based on Drucker-Prager criterion function defined in '_rheology.py'. I believe in the denominator of the formula we should have: sqrt(3) * (3 - sin(phi)). I'm attaching a screenshot of what I have seen in the code here.

![Screen Shot 2021-04-21 at 1 04 54 PM](https://user-images.githubusercontent.com/54119695/115860001-e55c8a80-a3fe-11eb-8c9e-3773ca90eb49.png)

**Comment by rbeucher** [comment]
Hi @alireza-bahadori,

Thanks for spotting this. I had a look... I know it's a bit late. I think you are right. I am trying to figure out how that mistake was made... I have changed the code and this will be fixed in 2.12.

Romain
