### ISSUE TITLE
y-shift in temperature recorded by passive tracers v.2.10.2

### ISSUE THREAD

**Issue by benedictecenki** [underworldcode/UWGeodynamics#232]
I have run a couple of experiments in v.2.10.2 with a series of passive tracers that shall track a few specific fields (e.g. temperature, pressure, materialField...).

It seems that there is a negative y-shift with the temperature (at least) recorded by the particle. 

As an example at t=0, for a particule located 5 km above the Moho (which is at 650°C), the real temperature is 639°C (reading isotherms) while the temperature recorded in the passive tracers table is 723°C (as if the particle was located a few km below the Moho). It seems to be the same for the material index as well (taken as if the particle was in the upper mantle, but it is indeed in the crust).

The overall pattern of particle depth-temperature paths through time seem internally consistent though.

Is it possible that there is an indexation shift ?

**Comment by julesghub** [comment]
Hi @benedictecenki, this sounds odd. 
Can you share the model file with me (privately if required) so I can investigate?

The good thing is this happens at t=0, so no significant computation is required to investigate the issue.

**Comment by rcarluccio** [comment]
Hi @benedictecenki,

I was just wondering what visualisation tool are you using? There have been a few times when paraview would give slightly different values, but simply plotting a depth profile through python would provide the expected value.

**Comment by julesghub** [comment]
Looks like a problem is when one asks the tracer particles to give output in "degC" for temperature, but the definition of the original temperature field is in "degK".
Can you switch the passive tracer output to "degK" and report back on the issue. Thanks.

**Comment by benedictecenki** [comment]
Thanks @julesghub I have re-ran a model just changing the unit of temperature to "degK" for the passive tracers. The temperature record of the passive tracers seem to match the model now and especially the phase change T. 

However the record of the material field index by the particles is still completely wrong. Can this be a unit problem as well ? (given that material has no unit we used a neutral unit but this may be the problem, if it is not an indexation one)

**Comment by benedictecenki** [comment]
@julesghub just noticed that the melt portion recorded by passive tracers is wrong as well

**Comment by julesghub** [comment]
> However the record of the material field index by the particles is still completely wrong. Can this be a unit problem as well ? (given that material has no unit we used a neutral unit but this may be the problem, if it is not an indexation one)

Yes i suspect it's a unit problem (not an indexation problem). 
Can you remove the `u.mol` units we added for the melt and material fields?

**Comment by benedictecenki** [comment]
If I remove the "units=u.mol", I get the follwing error:
TypeError: add_tracked_field() missing 1 required positional argument: 'units'

That's why we have tried to avoid the problem using a "neutral" unit. It seems to accept "units=1" but I am not sure about the implications. Any idea ?

**Comment by patrice-rey** [comment]
Try units = None

**Comment by benedictecenki** [comment]
The values for material and melt portion seem to be correct until the first restart. But after the first restart the values are wrong.

**Comment by benedictecenki** [comment]
Seems to be similar for the time field and viscosity field recorded by passive tracers as well...

**Comment by benedictecenki** [comment]
It seems that the problem occurs only when the model needs to be restarted ! We I start a run, the values recorded are correct but if the model stops, the values are wrong right after restarting it

**Comment by julesghub** [comment]
Hi @benedictecenki When you say the values seem wrong after the restart how are you accessing the values? Through python or the *.h5 files?

Please be aware that after a restart the `Lag_Grid` python object still references the initial tracer swarm - created prior to the restart. To reference the restarted Lag_Grid, after the restart operation, you MUST use the `Model.lag_grid_tracers` python object.

**Comment by benedictecenki** [comment]
> Hi @benedictecenki - I'm now looking at this. Pardon for the delay.
> 
> I have found checkpoint issues with UWGEO tracers swarms. I'm working on them now.
> 
> I think I have a quick workaround for the restart issue you've found.
> With your model you have commands like this to restart the model.
> 
> ```
> ## ACTIVATE THIS CELL FOR PHASE 2 (DELAMINATION)
> Model.run_for(60000000.* u.years, restartStep=1650, restartDir= "outputs_script-G48875-Cenki-etal_test1", checkpoint_interval=50000. * u.year)
> ```
> 
> If you arrange all the restart commands to just run, and NOT restart, i.e.
> `Model.run_for(60000000.* u.years, , checkpoint_interval=50000. * u.year)`
> then I imagine the restart issue tracer issue will disappear. Can you try that?
> 
> I know it's not a solution for the problem, but it's a workaround.
> I'll keep you posted with what I find re: checkpoint issues I've found.

Thanks @julesghub In this kind of model, which are sequential (I plan a series of steps with different boundary conditions building on each other) I guess this solution won't be of much use. In a one step model, there is no problem.

**Comment by benedictecenki** [comment]
> Hi @benedictecenki When you say the values seem wrong after the restart how are you accessing the values? Through python or the *.h5 files?
> 
> Please be aware that after a restart the `Lag_Grid` python object still references the initial tracer swarm - created prior to the restart. To reference the restarted Lag_Grid, after the restart operation, you MUST use the `Model.lag_grid_tracers` python object.

@julesghub to check the values, I am looking through the spreadsheet view (Paraview) at the Lag_grid.xdmf file.

The command line to record the passive tracers values is currently (as an example for the material field)
Lag_Grid.add_tracked_field(Model.materialField, name="LagGridMaterialField", units=None, dataType="

What would be the command line to use after restart to call the Material field of the Model.lag_grid_tracers ?

thanks

**Comment by julesghub** [comment]
Hi @benedictecenki,  we have identified what's causing this error. Essentially "stale" references to old data structures were available after a restart. Your model and UWGeo documentation was previously using these "stale" references.

The fix here will stop the problem e9b9617f99f5a857ff5d43b0e28efa539dcfed64 and will be available in the upcoming 2.12 release.

Note your notebook will need minor changes to compile with the 2.12 changes, I can help you with that.

**Comment by julesghub** [comment]
I'll close the ticket for now, feel free to reopen if you like.
