### ISSUE TITLE
"You have not passed anything to the temperature argument." when running testing examples on Gadi.

### ISSUE THREAD

**Issue by Peigen-L** [underworldcode/UWGeodynamics#233]
Hi, 

I am running the testing code "`UWGeodynamics/benchmarks/2D_Self_Subduction_Case1`" on Gadi.

And the error message recalled as: 
`/g/data/jq14/lp5029/codes/UWGeodynamics_2.9.6/lib/python3.9/site-packages/UWGeodynamics/_model.py:1524: UserWarning: You have not passed anything to the temperature argument. The temperature field will not be initialised
  warnings.warn("You have not passed anything to the temperature argument. The temperature field will not be initialised")`

I am using underworld version
`python3
>>> import underworld
>>> underworld.__version__
'2.10.1b'
>>>
`
Please help with this issue.

Kind regards
Peigen

**Comment by julesghub** [comment]
Hi @Peigen-L,
I notice the version of UWGeodynamics you are using is `2.9.6`, but the version of underworld is `2.10.1b`.
I suspect this is the problem. 2.9 UWGeo should only be run with 2.9 UW. This is how we structure the releases of the UWGeo. (Note the final version digit shouldn't matter) 
 
I was able to run this model in the docker `underworldcode/uwgeodynamics:v2.9.5`, which uses UWGeo `2.9.5` and UW `2.9.4b`

There are centrally installed version of  UWGeo on gadi with compatible underworld versions per release. They are located under `/g/data/m18/codes`. Not sure if you have access to that directory?
To use the gadi UWGeo-2.9 release you need to run:
`$ source /g/data/m18/codes/UWGeodynamics_2.9.sh` 
to setup your gadi environment.

**Comment by Peigen-L** [comment]
Solved, Thank you Julian. @julesghub
