### ISSUE TITLE
The XDMF.fields and XDMF.swarms show quite different pattern

### ISSUE THREAD

**Issue by longgangfan** [underworldcode/UWGeodynamics#236]
The materialField displayed in the paraview show quite different pattern between XDMF.fields  and XDMF.swarms.
![位图](https://user-images.githubusercontent.com/11954551/123531516-c3052700-d737-11eb-89f9-4dc42af7bb7d.png)
![位图2](https://user-images.githubusercontent.com/11954551/123531517-c8627180-d737-11eb-963c-2244544ef81e.png)
The two snapshots are from the same time step, one is material filed of  XDMF.fields, the other is material filed of XDMF.swarms.
One difference is the material 2 in two pictures show quite different shapes.
The other is that the interface between material 4 and 5 show obvious offset to the passive tracers in the XDMF.fields, but no offset in XDMF.swarms.

I am a newbie to Geodynamic modeling. Is it normal?

**Comment by julesghub** [comment]
The two images look quite different. Material 6 is different too. That's odd.

The difference between materialField and projMaterialFields. 
projMaterialFields is a projection of the swarm material indices ("materialField") to the mesh. i.e. particles to mesh projection. 
The projection will smear the distribution - and this depends on the resolution of the mesh used.
I'm not sure about the offset. Potentially improving the resolution could help this.
How many elements in the 2D mesh?

Hope some of this helps.

**Comment by longgangfan** [comment]
> The two images look quite different. Material 6 is different too. That's odd.
> 
> The difference between materialField and projMaterialFields.
> projMaterialFields is a projection of the swarm material indices ("materialField") to the mesh. i.e. particles to mesh projection.
> The projection will smear the distribution - and this depends on the resolution of the mesh used.
> I'm not sure about the offset. Potentially improving the resolution could help this.
> How many elements in the 2D mesh?
> 
> Hope some of this helps.
Thank you, you are right.  When I tried  a high resolution, the problem solved.
