### ISSUE TITLE
Tutorial 11 : Coupling a thermo-mechanical model with Badlands (2D) lost sed.time3.hdf5

### ISSUE THREAD

**Issue by longgangfan** [underworldcode/UWGeodynamics#240]
In the Tutorial 11, after running 2 steps, there are sed.time1.hdf5, sed.time2.hdf5, sed.time4.hdf5, sed.time5.hdf5 in the outbdls/h5. But the expected sed.time3.hdf5 is lost.

**Comment by longgangfan** [comment]
May be solved here https://github.com/badlands-model/badlands/issues/25#issuecomment-913524375

**Comment by gaowqspace** [comment]
Hi，thanks for your job！
I am a rookie for underworld and learning Tutorial_11. But I don't know the model's purpose or aim?  Can you give me some explanations？
