### ISSUE TITLE
Shape mismatch

### ISSUE THREAD

**Issue by ZhiqYu** [underworldcode/UWGeodynamics#246]
Hi 
I recently downloaded _Underworld2 v2.11.0_ and _UWGeodynamics v2.10.2_
When I run the file **tutorial_2_melt.ipynb** 
The following error occurs whenever **model.init_model()** is encountered
And I try to run other files **__.ipynb**, there is the same error
![1](https://user-images.githubusercontent.com/89136167/132699325-fcda083e-1022-4fcd-80d7-804bc3f7f883.jpg)

The file running under Docker is ok, but running on HPC found the error of shape mismatch
So I checked the code **local_y[Jpositions, Ipositions] = self.mesh.data[:self.mesh.nodesLocal, 1][:, np.newaxis]**
I find the difference between docker and our HPC 
Like this 
![2](https://user-images.githubusercontent.com/89136167/132699379-331085d1-a31c-4cc4-aae7-93a2608ccc4d.png)
![3](https://user-images.githubusercontent.com/89136167/132699392-329c59d6-f018-4374-8ba6-4f71d0a909f1.png)

Then we compared the two codes **underworld2\underworld\mesh\_mesh. py** and found the following two differences
![4](https://user-images.githubusercontent.com/89136167/132699429-fa93ffa0-23bd-4935-94c5-04b8d0004765.jpg)
![5](https://user-images.githubusercontent.com/89136167/132699455-93e202fe-2ae4-4108-8a30-bacc64217614.jpg)
What should we do to make the code work?

**Comment by patrice-rey** [comment]
Hi ZhiqYu,
In Underworld2 v2.11.0 the function Model.init_model() takes two attributes:  Model.init_model(temperature=True, pressureField=True).

**Comment by ZhiqYu** [comment]
Thanks
The Model.init_model() is ok, but the **Model.run_for()**is error
Like this 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-325-27c67c4c5683> in <module>
----> 1 Model.run_for(0.5 * u.megayears, checkpoint_interval=0.1*u.megayears)

~/.local/lib/python3.8/site-packages/UWGeodynamics/_model.py in run_for(self, duration, checkpoint_interval, nstep, checkpoint_times, restart_checkpoint, dt, restartStep, restartDir, output_units)
   1572             output_units, checkpoint_interval, duration)
   1573 
-> 1574         checkpointer = _CheckpointFunction(
   1575             self, duration, checkpoint_interval,
   1576             checkpoint_times, restart_checkpoint, output_dt_units)

~/.local/lib/python3.8/site-packages/UWGeodynamics/_model.py in __init__(self, Model, duration, checkpoint_interval, checkpoint_times, restart_checkpoint, output_units)
   2294 
   2295         if checkpoint_interval or checkpoint_times:
-> 2296             self.checkpoint_all()
   2297 
   2298     def checkpoint(self):

~/.local/lib/python3.8/site-packages/UWGeodynamics/_model.py in checkpoint_all(self, checkpointID, variables, tracers, time, outputDir)
   2373 
   2374         """
-> 2375         self.checkpoint_fields(variables, checkpointID, time, outputDir)
   2376         self.checkpoint_swarms(variables, checkpointID, time, outputDir)
   2377         self.checkpoint_tracers(tracers, checkpointID, time, outputDir)

~/.local/lib/python3.8/site-packages/UWGeodynamics/_model.py in checkpoint_fields(self, fields, checkpointID, time, outputDir)
   2415             mesh_name = 'mesh'
   2416             mesh_prefix = os.path.join(outputDir, mesh_name)
-> 2417             mH = Model.mesh.save('%s.h5' % mesh_prefix,
   2418                                  units=u.kilometers,
   2419                                  time=time)

~/.local/lib/python3.8/site-packages/UWGeodynamics/Underworld_extended/_mesh.py in save(self, filename, units, time)
    140         # write to the dset using the local set of global node ids
    141         with dset.collective:
--> 142             dset[self.data_nodegId[0:local],:] = self.data[0:local] * fact
    143 
    144         # write the element node connectivity

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/usr/local/anaconda3/lib/python3.8/site-packages/h5py-3.4.0-py3.8-linux-x86_64.egg/h5py/_hl/dataset.py in __setitem__(self, args, val)
    904 
    905         # Perform the dataspace selection
--> 906         selection = sel.select(self.shape, args, dataset=self)
    907 
    908         if selection.nselect == 0:

/usr/local/anaconda3/lib/python3.8/site-packages/h5py-3.4.0-py3.8-linux-x86_64.egg/h5py/_hl/selections.py in select(shape, args, dataset)
     80         selector = _selector.Selector(space)
     81 
---> 82     return selector.make_selection(args)
     83 
     84 

h5py/_selector.pyx in h5py._selector.Selector.make_selection()

h5py/_selector.pyx in h5py._selector.Selector.apply_args()

TypeError: Only 1D arrays allowed for fancy indexing

It is the same as this [https://github.com/underworldcode/UWGeodynamics/issues/229](url)

**Comment by patrice-rey** [comment]
.... I got around this by using the version 2.10.2.

**Comment by ZhiqYu** [comment]
Hi @patrice-rey 
Thank you for your reply！
But I also use the version 2.10.2

Error is as follows:

>>Model.run_for(nstep=2)

Running with UWGeodynamics version 2.10.2
Options:  -Q22_pc_type gkgdiag -force_correction True -ksp_type bsscr -pc_type none -ksp_k2_type NULL -rescale_equations False -remove_constant_pressure_null_space False -change_backsolve False -change_A11rhspresolve False -restore_K False -A11_ksp_type preonly -A11_pc_type lu -A11_pc_factor_mat_solver_type mumps -scr_ksp_type fgmres -scr_ksp_rtol 1e-05 -A11_mg_active False

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-c581722eb645> in <module>
----> 1 Model.run_for(nstep=2)

~/.local/lib/python3.8/site-packages/UWGeodynamics/_model.py in run_for(self, duration, checkpoint_interval, nstep, checkpoint_times, restart_checkpoint, dt, restartStep, restartDir, output_units)
   1599             self._pre_solve()
   1600 
-> 1601             self.solve()
   1602 
   1603             self._dt = 2.0 * rcParams["CFL"] * self.swarm_advector.get_max_dt()

~/.local/lib/python3.8/site-packages/UWGeodynamics/_model.py in solve(self)
   1477             maxIterations = rcParams["nonlinear.max.iterations"]
   1478 
-> 1479         self.solver.solve(
   1480             nonLinearIterate=True,
   1481             nonLinearMinIterations=minIterations,

~/underworld2/underworld/systems/_bsscr.py in solve(self, nonLinearIterate, nonLinearTolerance, nonLinearKillNonConvergent, nonLinearMinIterations, nonLinearMaxIterations, callback_post_solve, print_stats, reinitialise, **kwargs)
    446         # solve
    447         if nonLinear and nonLinearIterate:
--> 448             libUnderworld.StgFEM.SystemLinearEquations_NonLinearExecute(self._stokesSLE._cself, None)
    449         else:
    450             libUnderworld.StgFEM.SystemLinearEquations_ExecuteSolver(self._stokesSLE._cself, None)

RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
An error was encountered during the PETSc solver setup. You should refer to the PETSc
error message for details. Note that if you are running within Jupyter, this error
message will only be visible in the console window.

Server start failed:  'NoneType' object has no attribute 'family'
Server start failed:  'NoneType' object has no attribute 'family’

What should I do?

**Comment by julesghub** [comment]
Hi @ZhiqYu,
Underworld and UWGeodynamics are designed to be used with the same version numbers.
You mentioned the model worked on Docker but not on HPC. What versions of the code are you running on both platforms.
Use  
`$ python -c 'import UWGeodynamics as GEO; print("UWGeo/UW versions: ", GEO.__version__, GEO.underworld.__version__)'`

We recently released Underworld `2.11.0`  but UWGeodynamics `2.11.0`  has not been released yet, we aim to release it this week.

**Comment by ZhiqYu** [comment]
Thank you for your reply. @julesghub 
I have known the problem and look forward to the release of the new version

**Comment by julesghub** [comment]
Great to hear. If the problem is no longer an issue can you close the ticket? 

You can "watch" or "star" the UWGeodynamic GitHub repository to be notified when a new release comes out?

**Comment by ZhiqYu** [comment]
Hi @julesghub 
Can the problem be solved If I install Underworld2.10.2 and UWG 2.10.2 ？
But I have installed Underworld 2.10.2, Here's another question the same as[https://github.com/underworldcode/underworld2/issues/543](url)
