### ISSUE TITLE
2D surface processes implementation

### ISSUE THREAD

**Issue by bknight1** [underworldcode/UWGeodynamics#247]
Hi all,

I've written a file that adds surface processes into the UWGeodynamics framework (in 2D), through either (1) a diffusive surface or (2) using an erosion and sedimentation rate. 

I've tested both functions in serial and parallel and they work fine. I've added an example for each, with both examples based on tutorial 6.

I have a working version of erosion and sedimentation rates in 3D, however it needs some tiding up before sharing.

I can't upload the files directly so I have included all three files in a compressed folder.

Cheers,
Ben

[UWGeodynamics-SurfaceProcesses.zip](https://github.com/underworldcode/UWGeodynamics/files/7189058/UWGeodynamics-SurfaceProcesses.zip)

**Comment by patrice-rey** [comment]
Hi Ben, this looks very useful, thanks for sharing!

**Comment by julesghub** [comment]
This sounds promising Ben! :+1: 
Contributions like this are best shared as a Pull Request via GitHub. Would you be able to make one? 
We have guidelines for it here https://github.com/underworldcode/UWGeodynamics#how-to-create-a-pull-request-pr

Let me know how you go.

**Comment by bknight1** [comment]
Thanks @patrice-rey and @julesghub 

I'll give it a go @julesghub and let you know how I get on

**Comment by rbeucher** [comment]
Thanks @bknight1. I'll have a look.
