### ISSUE TITLE
Something wrong about PETSc

### ISSUE THREAD

**Issue by ZhiqYu** [underworldcode/UWGeodynamics#251]
Hello
First of all ，I am happy to be able to use UWG 2.11！
But
When I ran the example in the _tutorial,_ I encountered the following error with **model.run_for()**

Running with UWGeodynamics version 2.11.0-dev-485ad28(master)

Options:  -Q22_pc_type gkgdiag -force_correction True -ksp_type bsscr -pc_type none -ksp_k2_type NULL -rescale_equations False -remove_constant_pressure_null_space False -change_backsolve False -change_A11rhspresolve False -restore_K False -A11_ksp_type preonly -A11_pc_type lu -A11_pc_factor_mat_solver_type mumps -scr_ksp_type fgmres -scr_ksp_rtol 1e-05 -A11_mg_active False

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-39-cd4e1dff3bce> in <module>
----> 1 Model.run_for(5000.* u.years, checkpoint_interval=1000. * u.year)

~/.local/lib/python3.8/site-packages/UWGeodynamics/_model.py in run_for(self, duration, checkpoint_interval, nstep, checkpoint_times, restart_checkpoint, dt, restartStep, restartDir, output_units)
   1638             self._pre_solve()
   1639 
-> 1640             self.solve()
   1641 
   1642             self._dt = 2.0 * rcParams["CFL"] * self.swarm_advector.get_max_dt()

~/.local/lib/python3.8/site-packages/UWGeodynamics/_model.py in solve(self)
   1480             maxIterations = rcParams["nonlinear.max.iterations"]
   1481 
-> 1482         self.solver.solve(
   1483             nonLinearIterate=True,
   1484             nonLinearMinIterations=minIterations,

~/underworld2/underworld/systems/_bsscr.py in solve(self, nonLinearIterate, nonLinearTolerance, nonLinearKillNonConvergent, nonLinearMinIterations, nonLinearMaxIterations, callback_post_solve, print_stats, reinitialise, **kwargs)
    446         # solve
    447         if nonLinear and nonLinearIterate:
--> 448             libUnderworld.StgFEM.SystemLinearEquations_NonLinearExecute(self._stokesSLE._cself, None)
    449         else:
    450             libUnderworld.StgFEM.SystemLinearEquations_ExecuteSolver(self._stokesSLE._cself, None)

RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
An error was encountered during the PETSc solver setup. You should refer to the PETSc
error message for details. Note that if you are running within Jupyter, this error
message will only be visible in the console window.
<img width="810" alt="微信图片_20211017213636" src="https://user-images.githubusercontent.com/89136167/137629600-77e28705-a859-470b-b52b-7d5f612c31fe.png">

What should I do in this situation？

**Comment by julesghub** [comment]
Hi @ZhiqYu, can you please include the the error message from the console window?
Also what tutorial model was this?

**Comment by julesghub** [comment]
How are you running the docker. Via kitematic or on the command line? Either one will contain the complete error message.

**Comment by julesghub** [comment]
Hi @ZhiqYu ,
The error is because the petsc installation (a dependency of Underworld) you have doesn't include `mumps`. `mumps` is one of the solver packages petsc can use. For 2D Underworld models we recommend using it.

You can see `mumps` is used in the model here.
>
> Running with UWGeodynamics version 2.11.0-dev-485ad28(master)
>
> Options: -Q22_pc_type gkgdiag -force_correction True -ksp_type bsscr -pc_type none -ksp_k2_type NULL -rescale_equations  False -remove_constant_pressure_null_space False -change_backsolve False -change_A11rhspresolve False -restore_K False -A11_ksp_type preonly -A11_pc_type lu -A11_pc_factor_mat_solver_type mumps -scr_ksp_type fgmres -scr_ksp_rtol 1e-05 -A11_mg_active False

And this error msg from petsc confirms mumps it's available.
> [0]PETSC ERROR: Could not locate solver type mumps for factorization type LU and matrix type seqaij. Perhaps you must ./configure with --download-mumps

I suggest you either: 
1. use the Underworld Docker which includes `mumps`.
2. reinstall petsc on your machine using the configuration taken from our dockerfile, see https://github.com/underworldcode/underworld2/blob/b49640bf1a4cf480563d04552c8c9f7de230d20e/docs/development/docker/petsc/Dockerfile#L82
3. Don't use mumps, see https://uwgeodynamics.readthedocs.io/en/latest/UserGuide.html#dynamic-rc-settings

**Comment by rbeucher** [comment]
I am closing this. Feel free to reopen if needed.

**Comment by ZhiqYu** [comment]
ok 发自我的荣耀手机-------- 原始邮件 --------发件人： Romain Beucher ***@***.***>日期： 2021年11月25日周四 早上7:27收件人： underworldcode/UWGeodynamics ***@***.***>抄送： ZhiqYu ***@***.***>, Mention ***@***.***>主    题： Re: [underworldcode/UWGeodynamics] Something wrong about PETSc (Issue #251)
I am closing this. Feel free to reopen if needed.
