### ISSUE TITLE
Install UWgeodynamics latest on Macbook with M1 

### ISSUE THREAD

**Issue by HanyMKhalil** [underworldcode/UWGeodynamics#254]
Dear all, I have tried to install latest version of UWgeodynamics using Docker on my Macbook m1 but it says it is not compatible with ARM as it is amd64. I found a post y romain Buscher on how to install underworld on macbook with m1 but how can I adapt it to install UWgeodynamic and open it on jupyter notebook?

here is what Romain posted:
https://www.underworldcode.org/articles/how-to-install-underworld-on-mac-osx-big-sur-apple-silicon-m1/

**Comment by HanyMKhalil** [comment]
Hi Julian, Romain,

I am sorry had to open this again as I am now working on my mac m1 entirely and i use binder to adjust my codes online I upload the script change it, download it, then remove it so that it is not public, is that correct or I can leave my codes on binder workspace?

also I tried to follow Romain guide to install UWgeo on mac M1 but the problem is the brew function that is used to install doesnot exist on my mac terminal gives this error:
-bash: brew: command not found

I searche donline and i used many lines to install homebrew and brew on my mac but after it is successfuly installed whe I run brew help gives me same error, so I am not sure how can I proceed now??

any advise?

**Comment by HanyMKhalil** [comment]
Hi Julian, Romain,

I am sorry had to open this again as I am now working on my mac m1 entirely and i use binder to adjust my codes online I upload the script change it, download it, then remove it so that it is not public, is that correct or I can leave my codes on binder workspace?

also I tried to follow Romain guide to install UWgeo on mac M1 but the problem is the brew function that is used to install doesnot exist on my mac terminal gives this error:
-bash: brew: command not found

I searche donline and i used many lines to install homebrew and brew on my mac but after it is successfuly installed whe I run brew help gives me same error, so I am not sure how can I proceed now??

any advise?

**Comment by HanyMKhalil** [comment]
Hi all an update I was able to get the brew run now I have a probem with the h5py it always failed to install
i got this:

  ERROR: Failed building wheel for h5py
Failed to build underworld h5py
ERROR: Could not build wheels for underworld, h5py, which is required to install pyproject.toml-based projects

**Comment by rbeucher** [comment]
I think the new docker ARM64 images should fix this issue. I am closing it.
