### ISSUE TITLE
Strange proViscosity leap under lithostatic condition

### ISSUE THREAD

**Issue by longgangfan** [underworldcode/UWGeodynamics#256]
[test.py.txt](https://github.com/underworldcode/UWGeodynamics/files/7559777/test.py.txt)
From step 0 to step 1 (100000 year), the proViscosity of the crust get a big change, it is quite hard to understand. 
![0_step](https://user-images.githubusercontent.com/11954551/142350599-e9147fd8-0159-4b6d-a6e9-ac9a80fe1aa2.png)
![1_step](https://user-images.githubusercontent.com/11954551/142350610-8658a8e6-c223-4b6d-9152-bc6c07e169c7.png)

I run the model in the UWgeodynamics downloaded from dockehub lastest (2.10.5).

Any suggestion? Thank you.

**Comment by patrice-rey** [comment]
Yep it does. A time step 0 the boundary conditions are not yet applied. So the viscosity is simply function of the temperature. At time step 1 the boundary conditions are applied, and the viscosity, which probably depends on strain rate in you model, increases.

**Comment by longgangfan** [comment]
> Yep it does. A time step 0 the boundary conditions are not yet applied. So the viscosity is simply function of the temperature. At time step 1 the boundary conditions are applied, and the viscosity, which probably depends on strain rate in you model, increases.

My boundary conditions are as below:
`# Temperature
Model.set_temperatureBCs(top=293.15 * u.degK, bottom=893.15 * u.degK,
                         materials=[(stickyair, 293.15 * u.degK)])

# velocity
Model.set_velocityBCs(left=[0, None],
                      right=[0, None],
                      top=[None, None],
                      bottom=[None, 0])`

1e27 seems to be too large?

**Comment by patrice-rey** [comment]
Try to add a bit of velocity (2, 3 cm both sides) and see the result on the viscosity.

**Comment by longgangfan** [comment]
> Try to add a bit of velocity (2, 3 cm both sides) and see the result on the viscosity.

I think it will be OK, if I add a bit of velocity. But why the proViscosity is so large, when velocity = 0?

**Comment by patrice-rey** [comment]
viscosity = (deviatoric stress) / (strain_rate)

**Comment by longgangfan** [comment]
> viscosity = (deviatoric stress) / (strain_rate)

Thank you. Forgive my stupidity. But what make the viscosity larger  than geological common-sense in my boundary conditions? There is no situation where the velocity = 0 on earth? or these is no such low strain_rate?

**Comment by longgangfan** [comment]
Thank you, I think I know the point. I will close this issue.
