### ISSUE TITLE
A typo in the  PlasticRheologies.json 

### ISSUE THREAD

**Issue by longgangfan** [underworldcode/UWGeodynamics#258]
"Watremez et al., 2013 (LithosphericMantle)" in the line 180 should be "Watremez et al., 2013 ( AsthenosphericMantle)"
![截图_2021-12-17_11-07-49](https://user-images.githubusercontent.com/11954551/146485011-2482f3bb-a038-4c18-895e-641e7c698000.png)

**Comment by rbeucher** [comment]
Thanks!
