### ISSUE TITLE
Problem with Model.init_model() in v2.11

### ISSUE THREAD

**Issue by royarnab18** [underworldcode/UWGeodynamics#262]
Hello everyone
I keep getting a shape mismatch while running Model.init_model() in uwgeodynamics v2.11. Is there a workaround for this issue?
![Screenshot 2022-02-01 at 9 21 08 AM](https://user-images.githubusercontent.com/42836526/151948821-c9ebe8e7-b485-41d0-9192-49cef9aa6086.png)

**Comment by julesghub** [comment]
Hi @royarnab18 - are you sure your using v2.11?
The line causing where your error occurs has been modified in v2.11, ie https://github.com/underworldcode/UWGeodynamics/blob/485ad28cee2b9373a2c9673587e49a96c2e14150/UWGeodynamics/lithopress/lithopress.py#L98

How did you install the code?

**Comment by royarnab18** [comment]
Thanks for the reply. I am trying to run it in ARCHER2 using singularity. Should I reinstall the code?

**Comment by julesghub** [comment]
The singularity docker for UWGeo goes to version UWGeo 2.10 at present.
All example models/scripts with that docker should be self consistent with that version of the code.

Have you tried to run the example models - do they exhibit the same error?

**Comment by royarnab18** [comment]
Yes, it does actually. The same error persists in the docker container which I tried running on a mac.

**Comment by julesghub** [comment]
Which examples error?

**Comment by royarnab18** [comment]
I tried running Tutorial1. However, I found that the latest tag of the uwgeodynamics does not give this issue. I will close this for now. Thanks
