### ISSUE TITLE
Persistant problem for properties recorded by passive tracers after restart in v.2.12.4

### ISSUE THREAD

**Issue by benedictecenki** [underworldcode/UWGeodynamics#265]
This is a follow up for issue #232

The problem on properties recorded by passive tracers after restart seems to persist in v.2.12.4

I have attached four screenshost of paraview read for the properties recorded by passive tracers. Restart takes place at step 140. 
Values in steps 138 and 139 seem to be correct (make physical sense) and vary in a coherent manner. At step 140 some values (laggridmaterialfield, laggridmeltfield, laggridtimefield, laggridviscosity) are set and stuck to some values that are not correct (11, 0, 0 and 5e+21 respectively) and they do no vary anymore. 

<img width="730" alt="Step138-Restart-2" src="https://user-images.githubusercontent.com/78902016/157404877-65b48371-8b57-4ae9-80f8-04c05369ae4c.png">
<img width="721" alt="Step139-Restart-1" src="https://user-images.githubusercontent.com/78902016/157404898-b8176774-0ee4-454c-aaf5-a3de3094a3ca.png">
<img width="719" alt="Step140-Restart+1" src="https://user-images.githubusercontent.com/78902016/157404901-1abac343-664a-4756-b1a0-87995a9f8ff5.png">
<img width="728" alt="Step141-Restart+2" src="https://user-images.githubusercontent.com/78902016/157404905-8fe49315-fa0d-42e6-8bd3-44bd5abf94e2.png">

**Comment by julesghub** [comment]
I think the old (stale) python objects are still being used to create the hdf5 files for the lag tracers.
Are these models in the private repo we set up?

**Comment by benedictecenki** [comment]
Yes this is the model in public repository (UHT-granulitic-terranes) but activated for Model 1 (Fst_2RHP_diff) so that the restart occurs at 7 My after shortening

**Comment by julesghub** [comment]
@benedictecenki I have fixed up the restart issue as far as I can tell. Yay! It's a complicated explanation for the fix and reasoning behind it. So I'll leave it out here and just describe the changes need to get the fix.

1) Use the underworldcode/uwgeodyanamics:v2.12.5 docker (I made it earlier today so you'll have to download it) 
2) **Never** use any projected field in the passive tracer tracking. ie. any field prefixed with `Model.proj...` just use the original field instead.  Eg. `Model.projTimeField` -> `Model.timeField`
3) Checkout the 2.12 branch of the model. Here's a link to it. Please look through and make change to the file. NB I've left `run_for()` section commented out. https://github.com/underworld-community/cenki-et-al-UHT-granulitic-terranes/blob/v2.12/Script_ter12577_Cenki-etal_2022.ipynb

**Comment by benedictecenki** [comment]
I have re-run one experiment and there seem to be no disruption of the values recorded by passive tracers after restart! Thanks @julesghub
