### ISSUE TITLE
About Tutorial_11

### ISSUE THREAD

**Issue by gaowqspace** [underworldcode/UWGeodynamics#266]
Hi，thanks for your job！
I am a rookie for underworld and learning Tutorial_11. But I don't know the model's purpose or aim? 
Can you give me some explanations？

Thanks you again!

**Comment by patrice-rey** [comment]
Its purpose, like the purpose of any other tutorials, is to help you learn underworld.

**Comment by gaowqspace** [comment]
Sorry, I seem to be asking a silly question. I am try to understand it.
