### ISSUE TITLE
The number of particles in swarm has changed 

### ISSUE THREAD

**Issue by 42041030** [underworldcode/UWGeodynamics#269]
Hi guys，
    The number of particles in the Model.swarm is 160000, When I run the model for 100 years, the number is constant, but when  I run the model for 500 years, the number becomes 160018. I wonder why the number of particles is increasing, and how to prevent the number of particles from increasing over time ？
    My underworld version is 2.10.1b. The boundaries of the model are set to be fixed， the size and boundary conditions of the model are

Model = GEO.Model(elementRes=(100, 40),
                  minCoord=(0. * u.kilometer, -1.5 * u.kilometer), 
                  maxCoord=(25. * u.kilometer,3 * u.kilometer), 
                  gravity=(0.0, -9.81 * u.meter / u.second**2))
Model.mesh_advector(axis=0) 

Model.set_velocityBCs(left=[0 ,None],
                      right=[0,None],
                      top=[None,0],
                      bottom=[None,0])                  
Model.init_model()
Model.solver.set_penalty(1e4)
Model.solver.set_inner_method("mumps")

Thanks

**Comment by patrice-rey** [comment]
The number of particles is not meant to stay constant. Particles split or merge to ensure that cells are reasonably populated.

**Comment by 42041030** [comment]
I see. Thank you very much
