### ISSUE TITLE
model results visualization

### ISSUE THREAD

**Issue by gaowqspace** [underworldcode/UWGeodynamics#271]
I opened tutorial_11 operation results _outbdl_ with _Paraview-xdmf reader_. _flow.series.xdmf_ and _tin.series.xdmf_ could load, but when I click play button, the visualization results was far from what I expected. It doesn't have 3D effection and looks like flat.

Can you tell me what is the correct way to load output results with Paraview?

Thank you!

**Comment by patrice-rey** [comment]
Have you scaled the badlands output (scaling factor 0.0001 for x, y and z).

**Comment by patrice-rey** [comment]
Sure, look better.
In the window Properties "Scale" is under Transforming.

**Comment by gaowqspace** [comment]
Thansks for your reply!

Oh! I tried it before! This time I scaling  factor 0.0001 for x, y and z, but I saw the visualization results as same as before. I think 1:1:1 is equal to 0.0001:0.0001:0.0001 for x, y and z. Let me tell you more details about _Paraview_.

1. Run tutorial_11 in unmodifying its code.
2. Opened output results _tin.series.xdmf_with _Paraview-xdmf reader_.
3. Click _Apply_ and scale x, y and z to 0.0001.

I don't know where is the problem.

**Comment by patrice-rey** [comment]
Have you verified that there is some tin and flow .h5 files in the output folder?

**Comment by gaowqspace** [comment]
Thanks for your reply!

Yes! My output folder contains: 

- h5 folder. It includes some flow.timeT.hdf5. / sed.timeT.hdf5 / tin.timeT.hdf5.
- xmf folder. It includes some flow.timeT.xmf / tin.timeT.xmf.
- badlands.xml
- flow.series.xdmf
- tin.series.xdmf

**Comment by patrice-rey** [comment]
Then I do not know. 
Opening the .xdmf file in Paraview should work. Any error message?

**Comment by gaowqspace** [comment]
No any error message. It can work just look like a flat. I think it should be a 3D result.

Let me see. Thank you again!

**Comment by rbeucher** [comment]
Hi @gaowqspace ,

This is a Baldands issue so I am transferring it to Badlands.
However, you're output is normal. Badlands surfaces are 2D. You can obtained a 3D surface by applying a calculator filter.
![Screenshot from 2022-05-23 09-55-20](https://user-images.githubusercontent.com/3680918/169721722-f04c0655-ec06-439e-b5e7-c2e67870d937.png)

Note that this is how I do it but I recall @tristan-salles uses a different approach.
