### ISSUE TITLE
About xdmf files produced from tutorial 3

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/UWGeodynamics#53]
Hi~
I'm a beginner @____@ 

I run the > Tutorial 3: The Numerical Sandbox, Extension Experiment (Mesh deform version) 

with kitematic

I found the xdmf files produced from tutorial made paraview break down easily.
however they could open by visit

I thought if there were something wrong in the parameter "Model run" or not

I just guess, I'm looking for debugs and compare programs with underworld2

sorry to disturb

**Comment by cgw0814** [comment]
Oh~ BTW, I like UWGeodynamics, is it a open source? I found this information in underworld2 @@, if not I'm sorry to use without your agreement.

**Comment by rbeucher** [comment]
Thanks @cgw0814 ! I will check that out.
The code is opensource, you can use it and I am also open to suggestions. May I suggest you click the star on the right top corner on Github? (That's good for our stats ;-))
The code as a DOI you can use if you use it for publication.
It is fairly new and could do with more users! Do not hesitate to share it!

**Comment by cgw0814** [comment]
@rbeucher Thanks for your open share, I have click star 👍
