### ISSUE TITLE
[suggestion] Revise model initialization

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/UWGeodynamics#66]
Just to enable mesh refinements, i guess swarm initialization could be deferred if a meshModification flag is passed on to the model initialization and called(e.g. Model.init_swarms() ) by user after he/she/they have made modification to the mesh. 
Any Ideas?
if you favour this one i could send in a PR for review

**Comment by rbeucher** [comment]
Not sure I follow. You can send the PR

**Comment by arijitlaik** [comment]
something like this
```python
import UWGeodynamics as GEO

model = GEO.Model(
    elementRes=(24, 16),
    minCoord=(0., 0),
    maxCoord=(24., 16.),
    gravity=(0.0, -9.81),
    periodic=(False, False),
    deferSwarmInit=True) # flag that prevents initialization of swarm and swarm variables

mesh = model.mesh

# do modification/refinements
with mesh.deform_mesh():
    mesh.data[:, 0] = mesh.data[:, 0]+100

# initialize swarm after mesh refinements to avoid empty cells etc
model.init_swarms()

model.add_material()
```

**Comment by rbeucher** [comment]
You don't need that for mesh refinement.

**Comment by arijitlaik** [comment]
actually, if the refinement is a bit too aggressive then some cell remain empty, and throw in an error and the particle distributions are according to a uniform mesh.

**Comment by rbeucher** [comment]
What layout do you use for the swarm? De
Default is percell so if the population control does its job you should not get any empty cell

**Comment by arijitlaik** [comment]
ya, i do not change the default percelllayout, but the current workflow to modify the mesh in UWGeo is something like this:
```
import UWGeodynamics as GEO

model = GEO.Model(
    elementRes=(24, 16),
    minCoord=(0., 0),
    maxCoord=(24., 16.),
    gravity=(0.0, -9.81),
    )
mesh = model.mesh

# do modification/refinements
with mesh.deform_mesh():
    mesh.data[:, 0] = mesh.data[:, 0]+100 # or any generic modifications
```
but in this way we have a swarm laid out on the orginal un modified mesh, if the modifcation is not too aggressive it is okay, but incase it is a but too aggressive then there is quite a bit of chance that there are empty cells, and this could throw in errors when we go to run/solve.
the workaround is to go a repopulation and updateowners after the mesh refinement/modification, but i guess it makes sense to allow user modification/refinement of the mesh, and they lay out the swarm by explicitly calling the model.init_swarms() functions would would layout the swarm(and the swarm variables ) in the modified mesh

**Comment by rbeucher** [comment]
Not sure. Let put this on hold for now. I am going through the documentation for now. Will see for enhancements later.

**Comment by arijitlaik** [comment]
okay.

**Comment by rbeucher** [comment]
I think we could have a Model.deform_mesh method instantiating a basic mesh refinement class that could be use like the classic deform mesh context. This could update the swarm and do all the necessary changes...

**Comment by arijitlaik** [comment]
Yes, sounds good, but isn't is just better to initialize/populate the swarm after deformation? then again this might not be good as other init's depend on the swarm

**Comment by rbeucher** [comment]
Yes of course but model initialisation does not take so much time. Easier to hide this from the user...I'll think about it
