### ISSUE TITLE
Gravity has flipped!

### ISSUE THREAD

**Issue by LukeMondy** [underworldcode/UWGeodynamics#84]
Hello,

I was getting very unexpected behavior in my models, where at t=0 everything looked OK, but then at t=1, my entire pressure field would flip (so high pressure in the air, low in the mantle) - but my velocities were still pointing up (that being, material was flowing from low to high pressure)!

After much confusion, I discovered that by defining gravity as a vector, rather than a scalar, it has lost its sign somehow:
https://github.com/underworldcode/UWGeodynamics/blob/f93fbfcf60b2da12efc450810e6a6dfbb7e91683/UWGeodynamics/_model.py#L45

My fix was to define gravity in my models as such:
```python
 Model = GEO.Model(elementRes=resolution,
                   minCoord=(-300 * u.kilometer, -180 * u.kilometer),
                   maxCoord=( 300 * u.kilometer,  20 * u.kilometer),
                   gravity = (0., -9.81 * u.m / u.s**2),                                                                                 
                   outputDir = output_dir)

```

Cheers,
Luke

**Comment by rbeucher** [comment]
oups... too much InSight watching...
226d6a85a2c946958af599327b03aaef6cce982b

**Comment by rbeucher** [comment]
No I was not testing for this at all.... It was fine with the gravity upward... I have a test that check the image output of the Stokes Sinker. I am going to turn that on...
