### ISSUE TITLE
Issue with restarts

### ISSUE THREAD

**Issue by LukeMondy** [underworldcode/UWGeodynamics#85]
Hello,

Just experiencing a bit of trouble with restarting a model. So I run this model: https://github.com/LukeMondy/Continental_Rifting/blob/master/lmondy_rift.py

for 300,000 years, which produces 3 checkpoints.

When I re-run the model, it writes this out:
```
Running with UWGeodynamics version 1.0.1
================================================================================

Restarting Model from Step 3 at Time = 0.0 year

(2018-12-14 13:49:17)
================================================================================
```
which is printed by: https://github.com/underworldcode/UWGeodynamics/blob/9abed9264c6f05bacdf9b048fbf8ce7d8ee86d44/UWGeodynamics/_model.py#L2567

So the bit that is weird is that it knows that `Step 3` is the right one, but the `Time = 0.0 year` is not right. As the model progresses, it essentially overwrites the earlier model:
`Step:     1 Model Time: 10000.00 year dt: 10000.00 year (2018-12-14 13:50:40)`

Any ideas?

**Comment by LukeMondy** [comment]
The latest bit of fix does not quite work.

First of all, I think https://github.com/underworldcode/UWGeodynamics/blob/4dac9dbce67aeefe52631fdcdbdd4a0851bfad69/UWGeodynamics/_model.py#L2567
should be:
```python
        Model.time = MPI.COMM_WORLD.bcast(Model.time, root=0)
```
and secondly, I don't think MPI can broadcast complex objects - and by this point, it has already been converted into a `Quantity` object:
https://github.com/underworldcode/UWGeodynamics/blob/4dac9dbce67aeefe52631fdcdbdd4a0851bfad69/UWGeodynamics/_model.py#L2563
I think you will have to load the time as a float, broadcast it, and then turn it into a quantity, something like this:
```python
        time = None
        # Get time from swarm-%.h5 file
        if uw.rank() == 0:
            swarm_file = os.path.join(self.restartDir, "swarm-%s.h5" % step)
            with h5py.File(swarm_file, "r") as h5f:
                time = float(h5f.attrs.get("time"))
        else:
            time = None

time = MPI.COMM_WORLD.bcast(time, root=0)
uw.barrier()
Model.time = u.Quantity(time)  # not really sure what should be here, but translating the float to a time. Not sure how to deal with scaling, etc.
```

**Comment by rbeucher** [comment]
OK I have pushed another fix to master. I have merged into dev...

**Comment by rbeucher** [comment]
I'm tuning the interface of the solver so that we can use all Petsc options... Dev was too far ahead and I did not bother pushing things.... 
Let me know if it works and I will up the version to 1.0.2
