### ISSUE TITLE
Trouble with restarting

### ISSUE THREAD

**Issue by patrice-rey** [underworldcode/UWGeodynamics#86]
Hi Romain,
It looks like the restart does not work. The model goes through the loading procedure but then stopped.
Cheers
Patrice
 

=========================================================================== Restarting Model from Step 93 at Time = 0.0 year
 
(2018-12-14 02:59:46)
===========================================================================
 
Mesh loaded(2018-12-14 02:59:46)
Swarm loaded(2018-12-14 02:59:50)
pressureField loaded(2018-12-14 02:59:52)
velocityField loaded(2018-12-14 02:59:53)
materialField loaded(2018-12-14 02:59:56)
plasticStrain loaded(2018-12-14 02:59:58)
temperature loaded(2018-12-14 02:59:59)
FSE_Mantle loaded(2018-12-14 02:59:59)

**Comment by rbeucher** [comment]
Let me know
