### ISSUE TITLE
Stress BC issue when restarting

### ISSUE THREAD

**Issue by LukeMondy** [underworldcode/UWGeodynamics#88]
Hi Romain,

We spoke about this last week, but restarting a model with a pressure BC has very odd effects. They seem to be independant of the model state too (restarting a model from timestep = 1 or timestep = 100 gives a similar outcome).

I have a simple model here: https://gist.githubusercontent.com/LukeMondy/8a5c0cb0d4953de1e05a6ea25e2d5085/raw/7072e5dbd93553505a88696c5fe138d67e24ef3f/stressBC_issue.py

You can see in this video a model that starts with a stress BC, runs for 5e6 years, is then restarted, and runs for another 5e6 years:
https://giphy.com/gifs/2mCSvMdixwUiE9Nb2x/html5
The left hand side shows the swarm, coloured by material index, and the right hand side shows the total pressure along the bottom wall.

The most obvious thing that is weird is that after the restart, the deformations changes a lot, and gets into a "lumpy" steady-state. The cause of this (I think) is that the pressure at the bottom of the model before the restart fluctuates, presumably in response to some dynamic pressures - but after the restart it stays fixed.

Any ideas?

(side note: I know my way of saving and reloading the pressure is weird, but this happens with or without that)

**Comment by LukeMondy** [comment]
With the [change](https://github.com/underworldcode/UWGeodynamics/commit/4bcccc752bd94dcb3dc9ff3e0e675176405dc9df), I see the same result.

What is the proper way to do a restart with a stress BC? Do I need to add the `tractionField` to the restart fields?
I updated the gist link with a model that works with the new solver options (though I did have to comment out this line: https://github.com/underworldcode/UWGeodynamics/blob/f581e7ef4ff5ab84571e19a7039eb4e85cde3b13/UWGeodynamics/_model.py#L1500)

**Comment by rbeucher** [comment]
Have you tried to redefined the stressBCs right after the restart method?
```
Model.restart()
Model.set_StressBCs()
Model.run_for()
```

**Comment by LukeMondy** [comment]
I don't call the `Model.restart()` function myself, I use the `Model.run_for(..., restartStep = -1, ...)` to do the restarting.
I can't see anything in the `restart()` that should affect the boundary conditions.

I'm not sure what the tractionField does, to be honest, so I don't know if adding it to the restart fields is good or not.

After you changed the code, did the model I linked run OK for you?

**Comment by rbeucher** [comment]
Ok so the workaround is to do a restart, change the BC, and run. I will change things so that it is more straightforward

**Comment by rbeucher** [comment]
OK I have just tried... There is something wrong. I'll try to sort that out before leaving...

**Comment by LukeMondy** [comment]
great, thanks a lot!

**Comment by rbeucher** [comment]
I had a look today and there might be an Underworld bug...I have done a pure underworld example and get the same behaviour... I'll try to investigate further tomorrow...

**Comment by LukeMondy** [comment]
Happy new year! Did you manage to find anything out?

**Comment by rbeucher** [comment]
Have not looked into that yet

**Comment by rbeucher** [comment]
OK so after some investigation it looks like the issue had nothing to do with https://github.com/underworldcode/underworld2/issues/357

I have made some changes to the way I create the solver object 7bcc582b6eff46d14cbad716b1a8e5adbe5812bf. This should work but feel free to reopen if it does not.

**Comment by LukeMondy** [comment]
Cool, thanks, testing it now.
