### ISSUE TITLE
Timefield resets on restart

### ISSUE THREAD

**Issue by LukeMondy** [underworldcode/UWGeodynamics#89]
Hi Romain,

I've noticed that after a restart, all the sediments loose their time of deposition. I think it's because of this line:
https://github.com/underworldcode/UWGeodynamics/blob/f59ae5190158c4672b9461d6096931142c88b529/UWGeodynamics/_model.py#L289

Cheers,
Luke

**Comment by rbeucher** [comment]
I have added timeField to the restart variables.
96c3560

**Comment by rbeucher** [comment]
I will close this. Feel free to reopen it.
