### ISSUE TITLE
Stress basal boundary condition not behaving properly

### ISSUE THREAD

**Issue by plovely** [underworldcode/UWGeodynamics#90]
Hi Romain,

Since starting with the new UWGeodynamics container, I have observed some notable differences between models that should be equivalent to those previously run with the underworld2_geodynamics container.  The geometry that evolves is significantly different and subsidence is too large.  I also notice that the vertical stress (calculated by integrating vertically density * gravity) deviates through time from the stress base boundary condition i have prescribed (from 3.61 GPa at the model start, which is equivalent to the basal boundary condition, to 3.33 GPa after 20 myr).  This drift did not occur in models run with the old container.  Is the implementation of the stress base boundary condition different in the new container?  This behavior looks similar to behavior of the lecode isostasy boundary condition, which we have discussed previously.

Here is the boundary condition I have set:
Model.set_velocityBCs(left=[-0.55 * u.centimeter / u.year, 0.0 * u.centimeter / u.year],
                       right=[0.55 * u.centimeter / u.year, 0.0 * u.centimeter / u.year],
                       bottom=[0.0 * u.pascal, 3.607e9 * u.pascal])

Thanks,
Pete

**Comment by rbeucher** [comment]
Hi Peter,

In the new implementation, Stress and Kinematic condition have been separated.

```python
Model.set_velocityBCs(left=[-0.55 * u.centimeter / u.year, 0.0 * u.centimeter / u.year],
right=[0.55 * u.centimeter / u.year, 0.0 * u.centimeter / u.year],
bottom=[0.0 * u.pascal, 3.607e9 * u.pascal])
```

Doing this will actually prescribe a kinematic boundary condition.

What you need to do:

```python
Model.set_velocityBCs(left=[-0.55 * u.centimeter / u.year, 0.0 * u.centimeter / u.year],
right=[0.55 * u.centimeter / u.year, 0.0 * u.centimeter / u.year])

Model.set_stressBCs(bottom=[0.0 * u.pascal, 3.607e9 * u.pascal])
```
Romain

**Comment by rbeucher** [comment]
I could check the dimensionality so that this raises an error...

**Comment by rbeucher** [comment]
I will close this one, feel free to reopen it if needed...
