### ISSUE TITLE
Petsc options printing seems to not be parallel safe

### ISSUE THREAD

**Issue by LukeMondy** [underworldcode/UWGeodynamics#91]
So this line here: https://github.com/underworldcode/UWGeodynamics/blob/dd8afd3ae5c6ef81a7cdb377fcdf3ee87cfd3cd2/UWGeodynamics/_model.py#L1546
weirdly seems to stop parallel models running for me. This is using the latest docker on my machine and on Magnus.
The rank 0 job gets stuck, and never seems to come out of this function.

Commenting it out makes things work fine. 

It's a good addition though, I like what it does! Not sure why it causes issues.

**Comment by arijitlaik** [comment]
Yes. same here.

**Comment by LukeMondy** [comment]
Looks like the function in UW is already parallel protected:
https://github.com/underworldcode/underworld2/blob/1c85883cc9ec11cc2298d30606103f38616ce10c/underworld/systems/_bsscr.py#L511

but the change:
https://github.com/underworldcode/UWGeodynamics/commit/9648c32023781558e6501d4d89d5e46f7731950b
did not fix it for me either.

**Comment by arijitlaik** [comment]
@LukeMondy the fix  [9648c32](https://github.com/underworldcode/UWGeodynamics/commit/9648c32023781558e6501d4d89d5e46f7731950b) does work for me but what it does is prints _petsc: None_ for other processors

**Comment by LukeMondy** [comment]
@arijitlaik it works for me on my laptop, but not on the supercomputer magnus.

**Comment by rbeucher** [comment]
@LukeMondy the latest image is 4 days old. Try to clean the cache on Magnus and pull the image again.

**Comment by arijitlaik** [comment]
@rbeucher  sure. 
done

**Comment by rbeucher** [comment]
I am closing this... Feel free to reopen
