### ISSUE TITLE
ipyparallel function in kitematic

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/UWGeodynamics#93]
I'm sorry to ask a stupid question@@"

I download the uwgeodynamics image in kitematic

My host has ipyparallel function for jupyter already but don't have this kind of function when I used kitematic

Is it normal @@?

**Comment by cgw0814** [comment]
I found I type 'ipycluster start' , it's work in contain. But the computing was still slow. 

If I execute .py.  Would that be ok for typing 'mpi run -n 4 python xxx.py' in contain terminal?

**Comment by rbeucher** [comment]
Hi @cgw0814 ,

Not a stupid question at all!
The way to go is to use a terminal inside your container and to run:
```mpirun -np 4 python xxx.py```

**Comment by cgw0814** [comment]
I just wonder how could I enable the IPython Clusters tab  in contain instead of typing ipycluster start in terminal inside the contain?

**Comment by rbeucher** [comment]
We do not support the ipython cluster yet...
