### ISSUE TITLE
Badlands/UWGeodynamic coupling but only z axis?

### ISSUE THREAD

**Issue by patrice-rey** [underworldcode/UWGeodynamics#94]
Hello Romain,
I have been running some coupled UWGeo-Badlands pull-apart models. My issue is that the landscape doesn't move laterally as expected, interestingly there is no issue with the vertical motion of the surface. It seems that either the lateral motion of the UWGeo surface is not passed to Badlands, or it is passed with the wrong scale. The motion of the Badlands grid seems to confirm that there is a scaling issue.
Cheers
Patrice

**Comment by rbeucher** [comment]
I Have checked the Pull Apart Model and the surface is advected in 3D.
I have also checked the code and the scaling is the same for all the dimensions of the velocity field.
That could be a Badlands issue... Is it on Raijin?

**Comment by patrice-rey** [comment]
Yes, on Raijin using dev Jan24 build. 
I don't think I am using anything fundamentally different, I am reproducing the UW1 models in terms of rheology and geometry, same solver etc ... The most drastic change is the geotherm, yours look a bit hot in particular at the surface. I am investigating a bit further and keep you posted...

**Comment by patrice-rey** [comment]
Perhaps there is something here...
I am using a constant basal pressure as a bottom boundary condition, but I didn't change the order_wall_conditions option in Model.set.velocityBC (see below). Should I add "bottom=None" in the velocityBCs?

====
Model.set_velocityBCs(left=[left_condition, None,   0.025 * u.centimeter / u.year],
                      right=[right_condition, None,  0.025 * u.centimeter / u.year],
                      front=[None, 0., None],
                      back=[None, 0., None],
                      order_wall_conditions=["top", "front", "back", "bottom", "left", "right"])

Model.set_stressBCs(bottom=[0.0, 0.0, 3.640e9 * u.pascal])
====

**Comment by rbeucher** [comment]
No I don't think it is needed. Your Model runs? Is the UW Model doing something sensible ?

**Comment by patrice-rey** [comment]
That's the interesting part, UW runs great and gives a nice pull-apart basin, the passive tracers at the surface of the crust move has requested, and even Badlands gives sensible results... but somehow the UW horizontal motion doesn't seems to be passed to Badlands.

**Comment by patrice-rey** [comment]
... I suspect that this is where the issue could be: The lines below are meant to put a grid of passive tracers 384 x 256 (i.e one particle every km) at the surface of the crust (z=0m). I switched from zOnly=True to False so these particles travel with the surface. Could this be a problem if these tracers are used to capture the velocity field?
====
xp = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), 384)
yp = np.linspace(GEO.nd(Model.minCoord[1]), GEO.nd(Model.maxCoord[1]), 256)

xp, yp = np.meshgrid(xp, yp)
xp = xp.flatten()
yp = yp.flatten()
zp = np.zeros(xp.shape)

surface_tracers = Model.add_passive_tracers(name="Surface Tracers", vertices=[xp, yp, zp], particleEscape=True, centroids=None, zOnly=False)
moho_tracers = Model.add_passive_tracers(name="Moho", vertices=[xp, yp, zp+GEO.nd(mantleLithosphere.top)], particleEscape=True, centroids=None, zOnly=False)

**Comment by rbeucher** [comment]
They are just tracers, they do not affect the Badlands part. You can indeed switch the horizontal advection for them if you want to. As I said, there is no tracers in the coupling.

**Comment by patrice-rey** [comment]
Hum, tricky one ... anyway, have a good weekend.

**Comment by patrice-rey** [comment]
Results of the week-end: The synchronisation between UWGeo and Badlands seems to depend on the characteristic velocity (which doesn't correspond to velocityBC/2), the length of the model, and possibly the velocity applied at the boundaries. Some associations between these parameters seem to work (i.e velocity = 1.0 cm/yr, length 256 km, velocityBCs=+/-2.56 cm/yr), but others don't (i.e velocity = 1.92 cm/yr, length 384 km, velocityBCs=+/-1.92 cm/yr) in which cases the landscape velocity is a fraction of the UWGeo velocity.

**Comment by rbeucher** [comment]
OK. I am going to check the scaling carefully.

**Comment by rbeucher** [comment]
Can you send me an example that does not work via email?

**Comment by patrice-rey** [comment]
Sure ...

**Comment by rbeucher** [comment]
I have spent quite a bit of time on this yesterday and I am confident that the scaling is correct. The values passed to Badlands are correct, in all cases you mentioned. I suspect that this is a Badlands problem.
I spoke with Tristan yesterday and it could be that the pb is that the horizontal displacements are greater than the regular grid resolution in Badlands... In your case it is about equal. We have not figure it out yet but I would expect the pb to disappear for velocities lower than 1.5cm / yr, which could explain why my Pull Apart and the one you have at 1.0 cm / year work...Badlands has the option to force discretisation of the horizontal displacement by setting the `time3d` value. You can try with something around 5000 years. I will do the test on my side. If it is the pb, I will try to figure out a way to automate that.

**Comment by rbeucher** [comment]
Pb would be resolution, and velocity BCs dependent which would explain the outcome of your tests...

**Comment by patrice-rey** [comment]
Thanks Romain, your explanation makes sense. I'll try a few test playing with the resolution. Cheers

**Comment by rbeucher** [comment]
So there's a fix here 2521d1f963fa43d759a911d00427da7e8257f9dd
Let us know if you have any issue.

**Comment by rbeucher** [comment]
Any luck with this? I will close the issue. Feel free to reopen if there is a pb.

**Comment by patrice-rey** [comment]
Hi Romain

All good, I meant to post a message on github yesterday to say that the Tristan’s correction on Badlands did fix the problem.

The Badlands surface is now synchronised with UWGeo surface.

Cheers

Patrice

Associate Professor Patrice Rey
School of Geosciences
Earthbyte Research Group
ARC - ITRH Basin Genesis Hub
Tel: 02 9351 2067
http://www.geosci.usyd.edu.au/users/prey/
patrice.rey@sydney.edu.au

On 12 Mar 2019, at 7:40 AM, Romain Beucher <notifications@github.com<mailto:notifications@github.com>> wrote:


Any luck with this? I will close the issue. Feel free to reopen if there is a pb.

**Comment by rbeucher** [comment]
Great, that's good news. It cost us a few days and some headaches but it's fine now...
