### ISSUE TITLE
running 3D-model-GEO.LecodeIsostasy problem

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/UWGeodynamics#97]
When I tried to run 3D model in docker, the processing always be interrupted by following massage

`You may need to check your initial particle layout configuration. A per cell layout might give better results than a global layout, especially where you have a deformed mesh. Also, if particles are allowed to escape the domain, you will need to set the 'particleEscape=True' swarm constructor parameter, and likely also the 'aggressive=True' population control constructed parameter.
application called MPI_Abort(comm=0x84000002, 1) - process 8
    Model.run_for(0.01 * u.megayear, checkpoint_interval=0.005 * u.megayear)
  File "/usr/local/lib/python2.7/dist-packages/pint/registry_helpers.py", line 216, in wrapper
    return func(*values, **kwargs)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1605, in run_for
    libUnderworld.PICellerator.WeightsCalculator_CalculateAll( weights_calculator._cself, self._cself )
RuntimeError: Error encountered. Full restart recommended as exception safety notguaranteed. Error message:
Something went wrong in _PCDVC_Calculate3D: Problem has an under resolved cell (Cell Id = 0).`

I found the key point is `bottom=GEO.LecodeIsostasy(reference_mat=mantle, average=True)` for VelBCs setting. Possibly isn't it for 3D model?  

Afterward I set Velocity of bottom wall by fn.branching, it's successfully to run.

**Comment by rbeucher** [comment]
Hi @cgw0814,

LecodeIsostasy should work for 3D models. What version are you running 2.6.1 or 2.7.1?
That error means that one of a cell has lost its particles This usually happens when the velocity field ihas an anomaly. Cell id = 0 is the cell at the bottom left corner...It looks like a boundary condition issue at the corner. Can you send me your script by email?

**Comment by cgw0814** [comment]
Hi~ @rbeucher  sorry to reply so late, sure! I send it right now, thanks

**Comment by rbeucher** [comment]
I am closing this as it is Model specific...Will answer by email
