### ISSUE TITLE
Error when using CompositeViscosity

### ISSUE THREAD

**Issue by mitchellmcm27** [underworldcode/UWGeodynamics#98]
With a model that includes one or more CompositeViscosity, I get the error below. 

`Error: Failed to execute the callback function, please check if it's valid`

It points back to the `callback_post_solve` property of the `Model` object. I think the following code is the source of the error

```python
def callback_post_solve(self, value):
    ...
    for material in self.materials:
        if material.viscosity:
            material.viscosity.firstIter.value = False
```

because materials with CompositeViscosity objects do not have the `viscosity` property, rather they have a list of `viscosities`. 

I was able to work around this by setting `Model._callback_post_solve` to `None`, then putting the following in `Model.postSolveHook`, though this obviously isn't ideal:

```python
for material in Model.materials:
    if material.viscosity:
        if hasattr(material.viscosity, "viscosities"):
            for viscosity in material.viscosity.viscosities:
                viscosity.firstIter.value = False
        else:
            material.viscosity.firstIter.value = False
```

It seems to avoid the error. If I copy the same for loop as the `callback_post_solve` function above, I get this error:
`AttributeError: 'CompositeViscosity' object has no attribute 'firstIter'`
which presumably was being hidden before, because it was raised from some deep part of the code.

Edit: now that I look at it, I'm not sure my postSolveHook is actually doing what I think it is, but I think the source of the error is correct.

**Comment by rbeucher** [comment]
Good point... I will fix that

**Comment by rbeucher** [comment]
The pb is that the CompositeViscosity class inherits from the Rheology class but the parent class is not initialised:

There is a line missing in CompositeViscosity.__init__(...)
```
 super(CompositeViscosity, self).__init__()
```
I am going to push a fix to the master branch

**Comment by rbeucher** [comment]
That should fix it 32ff3d195af8c38d7186f8290d1da0ca5f8c0687

Let me know how it goes. I haven't used the Combined viscosities much...

**Comment by mitchellmcm27** [comment]
Wow that was fast! I had trouble the model to converge, had to simplify it, but it seems to work! At least, no more error after a solution occurs.

**Comment by rbeucher** [comment]
Great. I am going to close this. Feel free to reopen if needed
