### ISSUE TITLE
Phase change as described in readthedocs manual produces error

### ISSUE THREAD

**Issue by plovely** [underworldcode/UWGeodynamics#99]
The implementation of phase changes as described in the readthedocs manual produces an error (screenshot attached).  

![phasechangeerror](https://user-images.githubusercontent.com/30320218/54377463-2a743700-4653-11e9-856c-e241052b35c1.png)

The older syntax (below) does not produce an error, though I have not verified if the results are correct.

import underworld.function as fn
water.phase_changes = GEO.PhaseChange(condition=fn.input()[1] > 0.0, result=air.index)

**Comment by rbeucher** [comment]
Thanks Peter!
